/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HTTPError } from './HTTPError';
import {
    HTTPErrorFromJSON,
    HTTPErrorFromJSONTyped,
    HTTPErrorToJSON,
    HTTPErrorToJSONTyped,
} from './HTTPError';
import type { PagedResponsePropertyChild } from './PagedResponsePropertyChild';
import {
    PagedResponsePropertyChildFromJSON,
    PagedResponsePropertyChildFromJSONTyped,
    PagedResponsePropertyChildToJSON,
    PagedResponsePropertyChildToJSONTyped,
} from './PagedResponsePropertyChild';

/**
 * 
 * @export
 * @interface ApiResponsePagedResponsePropertyChild
 */
export interface ApiResponsePagedResponsePropertyChild {
    /**
     * 
     * @type {PagedResponsePropertyChild}
     * @memberof ApiResponsePagedResponsePropertyChild
     */
    data?: PagedResponsePropertyChild | null;
    /**
     * 
     * @type {HTTPError}
     * @memberof ApiResponsePagedResponsePropertyChild
     */
    error?: HTTPError | null;
}

/**
 * Check if a given object implements the ApiResponsePagedResponsePropertyChild interface.
 */
export function instanceOfApiResponsePagedResponsePropertyChild(value: object): value is ApiResponsePagedResponsePropertyChild {
    return true;
}

export function ApiResponsePagedResponsePropertyChildFromJSON(json: any): ApiResponsePagedResponsePropertyChild {
    return ApiResponsePagedResponsePropertyChildFromJSONTyped(json, false);
}

export function ApiResponsePagedResponsePropertyChildFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponsePagedResponsePropertyChild {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : PagedResponsePropertyChildFromJSON(json['data']),
        'error': json['error'] == null ? undefined : HTTPErrorFromJSON(json['error']),
    };
}

export function ApiResponsePagedResponsePropertyChildToJSON(json: any): ApiResponsePagedResponsePropertyChild {
    return ApiResponsePagedResponsePropertyChildToJSONTyped(json, false);
}

export function ApiResponsePagedResponsePropertyChildToJSONTyped(value?: ApiResponsePagedResponsePropertyChild | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': PagedResponsePropertyChildToJSON(value['data']),
        'error': HTTPErrorToJSON(value['error']),
    };
}

