/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HTTPError } from './HTTPError';
import {
    HTTPErrorFromJSON,
    HTTPErrorFromJSONTyped,
    HTTPErrorToJSON,
    HTTPErrorToJSONTyped,
} from './HTTPError';
import type { PropertyChildDocument } from './PropertyChildDocument';
import {
    PropertyChildDocumentFromJSON,
    PropertyChildDocumentFromJSONTyped,
    PropertyChildDocumentToJSON,
    PropertyChildDocumentToJSONTyped,
} from './PropertyChildDocument';

/**
 * 
 * @export
 * @interface ApiResponseListPropertyChildDocument
 */
export interface ApiResponseListPropertyChildDocument {
    /**
     * 
     * @type {Array<PropertyChildDocument>}
     * @memberof ApiResponseListPropertyChildDocument
     */
    data?: Array<PropertyChildDocument> | null;
    /**
     * 
     * @type {HTTPError}
     * @memberof ApiResponseListPropertyChildDocument
     */
    error?: HTTPError | null;
}

/**
 * Check if a given object implements the ApiResponseListPropertyChildDocument interface.
 */
export function instanceOfApiResponseListPropertyChildDocument(value: object): value is ApiResponseListPropertyChildDocument {
    return true;
}

export function ApiResponseListPropertyChildDocumentFromJSON(json: any): ApiResponseListPropertyChildDocument {
    return ApiResponseListPropertyChildDocumentFromJSONTyped(json, false);
}

export function ApiResponseListPropertyChildDocumentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponseListPropertyChildDocument {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(PropertyChildDocumentFromJSON)),
        'error': json['error'] == null ? undefined : HTTPErrorFromJSON(json['error']),
    };
}

export function ApiResponseListPropertyChildDocumentToJSON(json: any): ApiResponseListPropertyChildDocument {
    return ApiResponseListPropertyChildDocumentToJSONTyped(json, false);
}

export function ApiResponseListPropertyChildDocumentToJSONTyped(value?: ApiResponseListPropertyChildDocument | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(PropertyChildDocumentToJSON)),
        'error': HTTPErrorToJSON(value['error']),
    };
}

