/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HTTPError } from './HTTPError';
import {
    HTTPErrorFromJSON,
    HTTPErrorFromJSONTyped,
    HTTPErrorToJSON,
    HTTPErrorToJSONTyped,
} from './HTTPError';
import type { PagedResponseProperty } from './PagedResponseProperty';
import {
    PagedResponsePropertyFromJSON,
    PagedResponsePropertyFromJSONTyped,
    PagedResponsePropertyToJSON,
    PagedResponsePropertyToJSONTyped,
} from './PagedResponseProperty';

/**
 * 
 * @export
 * @interface ApiResponsePagedResponseProperty
 */
export interface ApiResponsePagedResponseProperty {
    /**
     * 
     * @type {PagedResponseProperty}
     * @memberof ApiResponsePagedResponseProperty
     */
    data?: PagedResponseProperty | null;
    /**
     * 
     * @type {HTTPError}
     * @memberof ApiResponsePagedResponseProperty
     */
    error?: HTTPError | null;
}

/**
 * Check if a given object implements the ApiResponsePagedResponseProperty interface.
 */
export function instanceOfApiResponsePagedResponseProperty(value: object): value is ApiResponsePagedResponseProperty {
    return true;
}

export function ApiResponsePagedResponsePropertyFromJSON(json: any): ApiResponsePagedResponseProperty {
    return ApiResponsePagedResponsePropertyFromJSONTyped(json, false);
}

export function ApiResponsePagedResponsePropertyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponsePagedResponseProperty {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : PagedResponsePropertyFromJSON(json['data']),
        'error': json['error'] == null ? undefined : HTTPErrorFromJSON(json['error']),
    };
}

export function ApiResponsePagedResponsePropertyToJSON(json: any): ApiResponsePagedResponseProperty {
    return ApiResponsePagedResponsePropertyToJSONTyped(json, false);
}

export function ApiResponsePagedResponsePropertyToJSONTyped(value?: ApiResponsePagedResponseProperty | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': PagedResponsePropertyToJSON(value['data']),
        'error': HTTPErrorToJSON(value['error']),
    };
}

