/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HTTPError } from './HTTPError';
import {
    HTTPErrorFromJSON,
    HTTPErrorFromJSONTyped,
    HTTPErrorToJSON,
    HTTPErrorToJSONTyped,
} from './HTTPError';
import type { PagedResponsePropertyParentDocument } from './PagedResponsePropertyParentDocument';
import {
    PagedResponsePropertyParentDocumentFromJSON,
    PagedResponsePropertyParentDocumentFromJSONTyped,
    PagedResponsePropertyParentDocumentToJSON,
    PagedResponsePropertyParentDocumentToJSONTyped,
} from './PagedResponsePropertyParentDocument';

/**
 * 
 * @export
 * @interface ApiResponsePagedResponsePropertyParentDocument
 */
export interface ApiResponsePagedResponsePropertyParentDocument {
    /**
     * 
     * @type {PagedResponsePropertyParentDocument}
     * @memberof ApiResponsePagedResponsePropertyParentDocument
     */
    data?: PagedResponsePropertyParentDocument | null;
    /**
     * 
     * @type {HTTPError}
     * @memberof ApiResponsePagedResponsePropertyParentDocument
     */
    error?: HTTPError | null;
}

/**
 * Check if a given object implements the ApiResponsePagedResponsePropertyParentDocument interface.
 */
export function instanceOfApiResponsePagedResponsePropertyParentDocument(value: object): value is ApiResponsePagedResponsePropertyParentDocument {
    return true;
}

export function ApiResponsePagedResponsePropertyParentDocumentFromJSON(json: any): ApiResponsePagedResponsePropertyParentDocument {
    return ApiResponsePagedResponsePropertyParentDocumentFromJSONTyped(json, false);
}

export function ApiResponsePagedResponsePropertyParentDocumentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponsePagedResponsePropertyParentDocument {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : PagedResponsePropertyParentDocumentFromJSON(json['data']),
        'error': json['error'] == null ? undefined : HTTPErrorFromJSON(json['error']),
    };
}

export function ApiResponsePagedResponsePropertyParentDocumentToJSON(json: any): ApiResponsePagedResponsePropertyParentDocument {
    return ApiResponsePagedResponsePropertyParentDocumentToJSONTyped(json, false);
}

export function ApiResponsePagedResponsePropertyParentDocumentToJSONTyped(value?: ApiResponsePagedResponsePropertyParentDocument | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': PagedResponsePropertyParentDocumentToJSON(value['data']),
        'error': HTTPErrorToJSON(value['error']),
    };
}

