/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HTTPError } from './HTTPError';
import {
    HTTPErrorFromJSON,
    HTTPErrorFromJSONTyped,
    HTTPErrorToJSON,
    HTTPErrorToJSONTyped,
} from './HTTPError';
import type { PropertyParentDocument } from './PropertyParentDocument';
import {
    PropertyParentDocumentFromJSON,
    PropertyParentDocumentFromJSONTyped,
    PropertyParentDocumentToJSON,
    PropertyParentDocumentToJSONTyped,
} from './PropertyParentDocument';

/**
 * 
 * @export
 * @interface ApiResponseListPropertyParentDocument
 */
export interface ApiResponseListPropertyParentDocument {
    /**
     * 
     * @type {Array<PropertyParentDocument>}
     * @memberof ApiResponseListPropertyParentDocument
     */
    data?: Array<PropertyParentDocument> | null;
    /**
     * 
     * @type {HTTPError}
     * @memberof ApiResponseListPropertyParentDocument
     */
    error?: HTTPError | null;
}

/**
 * Check if a given object implements the ApiResponseListPropertyParentDocument interface.
 */
export function instanceOfApiResponseListPropertyParentDocument(value: object): value is ApiResponseListPropertyParentDocument {
    return true;
}

export function ApiResponseListPropertyParentDocumentFromJSON(json: any): ApiResponseListPropertyParentDocument {
    return ApiResponseListPropertyParentDocumentFromJSONTyped(json, false);
}

export function ApiResponseListPropertyParentDocumentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponseListPropertyParentDocument {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(PropertyParentDocumentFromJSON)),
        'error': json['error'] == null ? undefined : HTTPErrorFromJSON(json['error']),
    };
}

export function ApiResponseListPropertyParentDocumentToJSON(json: any): ApiResponseListPropertyParentDocument {
    return ApiResponseListPropertyParentDocumentToJSONTyped(json, false);
}

export function ApiResponseListPropertyParentDocumentToJSONTyped(value?: ApiResponseListPropertyParentDocument | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(PropertyParentDocumentToJSON)),
        'error': HTTPErrorToJSON(value['error']),
    };
}

