/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HTTPError } from './HTTPError';
import {
    HTTPErrorFromJSON,
    HTTPErrorFromJSONTyped,
    HTTPErrorToJSON,
    HTTPErrorToJSONTyped,
} from './HTTPError';
import type { PropertyChildDocumentRequirement } from './PropertyChildDocumentRequirement';
import {
    PropertyChildDocumentRequirementFromJSON,
    PropertyChildDocumentRequirementFromJSONTyped,
    PropertyChildDocumentRequirementToJSON,
    PropertyChildDocumentRequirementToJSONTyped,
} from './PropertyChildDocumentRequirement';

/**
 * 
 * @export
 * @interface ApiResponseListPropertyChildDocumentRequirement
 */
export interface ApiResponseListPropertyChildDocumentRequirement {
    /**
     * 
     * @type {Array<PropertyChildDocumentRequirement>}
     * @memberof ApiResponseListPropertyChildDocumentRequirement
     */
    data?: Array<PropertyChildDocumentRequirement> | null;
    /**
     * 
     * @type {HTTPError}
     * @memberof ApiResponseListPropertyChildDocumentRequirement
     */
    error?: HTTPError | null;
}

/**
 * Check if a given object implements the ApiResponseListPropertyChildDocumentRequirement interface.
 */
export function instanceOfApiResponseListPropertyChildDocumentRequirement(value: object): value is ApiResponseListPropertyChildDocumentRequirement {
    return true;
}

export function ApiResponseListPropertyChildDocumentRequirementFromJSON(json: any): ApiResponseListPropertyChildDocumentRequirement {
    return ApiResponseListPropertyChildDocumentRequirementFromJSONTyped(json, false);
}

export function ApiResponseListPropertyChildDocumentRequirementFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponseListPropertyChildDocumentRequirement {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(PropertyChildDocumentRequirementFromJSON)),
        'error': json['error'] == null ? undefined : HTTPErrorFromJSON(json['error']),
    };
}

export function ApiResponseListPropertyChildDocumentRequirementToJSON(json: any): ApiResponseListPropertyChildDocumentRequirement {
    return ApiResponseListPropertyChildDocumentRequirementToJSONTyped(json, false);
}

export function ApiResponseListPropertyChildDocumentRequirementToJSONTyped(value?: ApiResponseListPropertyChildDocumentRequirement | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(PropertyChildDocumentRequirementToJSON)),
        'error': HTTPErrorToJSON(value['error']),
    };
}

