/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HTTPError } from './HTTPError';
import {
    HTTPErrorFromJSON,
    HTTPErrorFromJSONTyped,
    HTTPErrorToJSON,
    HTTPErrorToJSONTyped,
} from './HTTPError';
import type { PropertyParentDocumentRequirement } from './PropertyParentDocumentRequirement';
import {
    PropertyParentDocumentRequirementFromJSON,
    PropertyParentDocumentRequirementFromJSONTyped,
    PropertyParentDocumentRequirementToJSON,
    PropertyParentDocumentRequirementToJSONTyped,
} from './PropertyParentDocumentRequirement';

/**
 * 
 * @export
 * @interface ApiResponseListPropertyParentDocumentRequirement
 */
export interface ApiResponseListPropertyParentDocumentRequirement {
    /**
     * 
     * @type {Array<PropertyParentDocumentRequirement>}
     * @memberof ApiResponseListPropertyParentDocumentRequirement
     */
    data?: Array<PropertyParentDocumentRequirement> | null;
    /**
     * 
     * @type {HTTPError}
     * @memberof ApiResponseListPropertyParentDocumentRequirement
     */
    error?: HTTPError | null;
}

/**
 * Check if a given object implements the ApiResponseListPropertyParentDocumentRequirement interface.
 */
export function instanceOfApiResponseListPropertyParentDocumentRequirement(value: object): value is ApiResponseListPropertyParentDocumentRequirement {
    return true;
}

export function ApiResponseListPropertyParentDocumentRequirementFromJSON(json: any): ApiResponseListPropertyParentDocumentRequirement {
    return ApiResponseListPropertyParentDocumentRequirementFromJSONTyped(json, false);
}

export function ApiResponseListPropertyParentDocumentRequirementFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponseListPropertyParentDocumentRequirement {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(PropertyParentDocumentRequirementFromJSON)),
        'error': json['error'] == null ? undefined : HTTPErrorFromJSON(json['error']),
    };
}

export function ApiResponseListPropertyParentDocumentRequirementToJSON(json: any): ApiResponseListPropertyParentDocumentRequirement {
    return ApiResponseListPropertyParentDocumentRequirementToJSONTyped(json, false);
}

export function ApiResponseListPropertyParentDocumentRequirementToJSONTyped(value?: ApiResponseListPropertyParentDocumentRequirement | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(PropertyParentDocumentRequirementToJSON)),
        'error': HTTPErrorToJSON(value['error']),
    };
}

