/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HTTPError } from './HTTPError';
import {
    HTTPErrorFromJSON,
    HTTPErrorFromJSONTyped,
    HTTPErrorToJSON,
    HTTPErrorToJSONTyped,
} from './HTTPError';
import type { PropertyParentDocument } from './PropertyParentDocument';
import {
    PropertyParentDocumentFromJSON,
    PropertyParentDocumentFromJSONTyped,
    PropertyParentDocumentToJSON,
    PropertyParentDocumentToJSONTyped,
} from './PropertyParentDocument';

/**
 * 
 * @export
 * @interface ApiResponsePropertyParentDocument
 */
export interface ApiResponsePropertyParentDocument {
    /**
     * 
     * @type {PropertyParentDocument}
     * @memberof ApiResponsePropertyParentDocument
     */
    data?: PropertyParentDocument | null;
    /**
     * 
     * @type {HTTPError}
     * @memberof ApiResponsePropertyParentDocument
     */
    error?: HTTPError | null;
}

/**
 * Check if a given object implements the ApiResponsePropertyParentDocument interface.
 */
export function instanceOfApiResponsePropertyParentDocument(value: object): value is ApiResponsePropertyParentDocument {
    return true;
}

export function ApiResponsePropertyParentDocumentFromJSON(json: any): ApiResponsePropertyParentDocument {
    return ApiResponsePropertyParentDocumentFromJSONTyped(json, false);
}

export function ApiResponsePropertyParentDocumentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponsePropertyParentDocument {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : PropertyParentDocumentFromJSON(json['data']),
        'error': json['error'] == null ? undefined : HTTPErrorFromJSON(json['error']),
    };
}

export function ApiResponsePropertyParentDocumentToJSON(json: any): ApiResponsePropertyParentDocument {
    return ApiResponsePropertyParentDocumentToJSONTyped(json, false);
}

export function ApiResponsePropertyParentDocumentToJSONTyped(value?: ApiResponsePropertyParentDocument | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': PropertyParentDocumentToJSON(value['data']),
        'error': HTTPErrorToJSON(value['error']),
    };
}

