/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HTTPError } from './HTTPError';
import {
    HTTPErrorFromJSON,
    HTTPErrorFromJSONTyped,
    HTTPErrorToJSON,
    HTTPErrorToJSONTyped,
} from './HTTPError';

/**
 * 
 * @export
 * @interface ApiResponseStr
 */
export interface ApiResponseStr {
    /**
     * 
     * @type {string}
     * @memberof ApiResponseStr
     */
    data?: string | null;
    /**
     * 
     * @type {HTTPError}
     * @memberof ApiResponseStr
     */
    error?: HTTPError | null;
}

/**
 * Check if a given object implements the ApiResponseStr interface.
 */
export function instanceOfApiResponseStr(value: object): value is ApiResponseStr {
    return true;
}

export function ApiResponseStrFromJSON(json: any): ApiResponseStr {
    return ApiResponseStrFromJSONTyped(json, false);
}

export function ApiResponseStrFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponseStr {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : json['data'],
        'error': json['error'] == null ? undefined : HTTPErrorFromJSON(json['error']),
    };
}

export function ApiResponseStrToJSON(json: any): ApiResponseStr {
    return ApiResponseStrToJSONTyped(json, false);
}

export function ApiResponseStrToJSONTyped(value?: ApiResponseStr | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'],
        'error': HTTPErrorToJSON(value['error']),
    };
}

