/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HTTPError } from './HTTPError';
import {
    HTTPErrorFromJSON,
    HTTPErrorFromJSONTyped,
    HTTPErrorToJSON,
    HTTPErrorToJSONTyped,
} from './HTTPError';
import type { ParentDocument } from './ParentDocument';
import {
    ParentDocumentFromJSON,
    ParentDocumentFromJSONTyped,
    ParentDocumentToJSON,
    ParentDocumentToJSONTyped,
} from './ParentDocument';

/**
 * 
 * @export
 * @interface ApiResponseParentDocument
 */
export interface ApiResponseParentDocument {
    /**
     * 
     * @type {ParentDocument}
     * @memberof ApiResponseParentDocument
     */
    data?: ParentDocument | null;
    /**
     * 
     * @type {HTTPError}
     * @memberof ApiResponseParentDocument
     */
    error?: HTTPError | null;
}

/**
 * Check if a given object implements the ApiResponseParentDocument interface.
 */
export function instanceOfApiResponseParentDocument(value: object): value is ApiResponseParentDocument {
    return true;
}

export function ApiResponseParentDocumentFromJSON(json: any): ApiResponseParentDocument {
    return ApiResponseParentDocumentFromJSONTyped(json, false);
}

export function ApiResponseParentDocumentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponseParentDocument {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ParentDocumentFromJSON(json['data']),
        'error': json['error'] == null ? undefined : HTTPErrorFromJSON(json['error']),
    };
}

export function ApiResponseParentDocumentToJSON(json: any): ApiResponseParentDocument {
    return ApiResponseParentDocumentToJSONTyped(json, false);
}

export function ApiResponseParentDocumentToJSONTyped(value?: ApiResponseParentDocument | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ParentDocumentToJSON(value['data']),
        'error': HTTPErrorToJSON(value['error']),
    };
}

