/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HTTPError } from './HTTPError';
import {
    HTTPErrorFromJSON,
    HTTPErrorFromJSONTyped,
    HTTPErrorToJSON,
    HTTPErrorToJSONTyped,
} from './HTTPError';
import type { PropertyChild } from './PropertyChild';
import {
    PropertyChildFromJSON,
    PropertyChildFromJSONTyped,
    PropertyChildToJSON,
    PropertyChildToJSONTyped,
} from './PropertyChild';

/**
 * 
 * @export
 * @interface ApiResponseListPropertyChild
 */
export interface ApiResponseListPropertyChild {
    /**
     * 
     * @type {Array<PropertyChild>}
     * @memberof ApiResponseListPropertyChild
     */
    data?: Array<PropertyChild> | null;
    /**
     * 
     * @type {HTTPError}
     * @memberof ApiResponseListPropertyChild
     */
    error?: HTTPError | null;
}

/**
 * Check if a given object implements the ApiResponseListPropertyChild interface.
 */
export function instanceOfApiResponseListPropertyChild(value: object): value is ApiResponseListPropertyChild {
    return true;
}

export function ApiResponseListPropertyChildFromJSON(json: any): ApiResponseListPropertyChild {
    return ApiResponseListPropertyChildFromJSONTyped(json, false);
}

export function ApiResponseListPropertyChildFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponseListPropertyChild {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(PropertyChildFromJSON)),
        'error': json['error'] == null ? undefined : HTTPErrorFromJSON(json['error']),
    };
}

export function ApiResponseListPropertyChildToJSON(json: any): ApiResponseListPropertyChild {
    return ApiResponseListPropertyChildToJSONTyped(json, false);
}

export function ApiResponseListPropertyChildToJSONTyped(value?: ApiResponseListPropertyChild | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(PropertyChildToJSON)),
        'error': HTTPErrorToJSON(value['error']),
    };
}

