/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HTTPError } from './HTTPError';
import {
    HTTPErrorFromJSON,
    HTTPErrorFromJSONTyped,
    HTTPErrorToJSON,
    HTTPErrorToJSONTyped,
} from './HTTPError';
import type { PropertyUser } from './PropertyUser';
import {
    PropertyUserFromJSON,
    PropertyUserFromJSONTyped,
    PropertyUserToJSON,
    PropertyUserToJSONTyped,
} from './PropertyUser';

/**
 * 
 * @export
 * @interface ApiResponsePropertyUser
 */
export interface ApiResponsePropertyUser {
    /**
     * 
     * @type {PropertyUser}
     * @memberof ApiResponsePropertyUser
     */
    data?: PropertyUser | null;
    /**
     * 
     * @type {HTTPError}
     * @memberof ApiResponsePropertyUser
     */
    error?: HTTPError | null;
}

/**
 * Check if a given object implements the ApiResponsePropertyUser interface.
 */
export function instanceOfApiResponsePropertyUser(value: object): value is ApiResponsePropertyUser {
    return true;
}

export function ApiResponsePropertyUserFromJSON(json: any): ApiResponsePropertyUser {
    return ApiResponsePropertyUserFromJSONTyped(json, false);
}

export function ApiResponsePropertyUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponsePropertyUser {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : PropertyUserFromJSON(json['data']),
        'error': json['error'] == null ? undefined : HTTPErrorFromJSON(json['error']),
    };
}

export function ApiResponsePropertyUserToJSON(json: any): ApiResponsePropertyUser {
    return ApiResponsePropertyUserToJSONTyped(json, false);
}

export function ApiResponsePropertyUserToJSONTyped(value?: ApiResponsePropertyUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': PropertyUserToJSON(value['data']),
        'error': HTTPErrorToJSON(value['error']),
    };
}

