/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const CHILDDOCUMENTTYPE = {
    DisabilityProof: 'disability_proof'
} as const;
export type CHILDDOCUMENTTYPE = typeof CHILDDOCUMENTTYPE[keyof typeof CHILDDOCUMENTTYPE];


export function instanceOfCHILDDOCUMENTTYPE(value: any): boolean {
    for (const key in CHILDDOCUMENTTYPE) {
        if (Object.prototype.hasOwnProperty.call(CHILDDOCUMENTTYPE, key)) {
            if (CHILDDOCUMENTTYPE[key as keyof typeof CHILDDOCUMENTTYPE] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CHILDDOCUMENTTYPEFromJSON(json: any): CHILDDOCUMENTTYPE {
    return CHILDDOCUMENTTYPEFromJSONTyped(json, false);
}

export function CHILDDOCUMENTTYPEFromJSONTyped(json: any, ignoreDiscriminator: boolean): CHILDDOCUMENTTYPE {
    return json as CHILDDOCUMENTTYPE;
}

export function CHILDDOCUMENTTYPEToJSON(value?: CHILDDOCUMENTTYPE | null): any {
    return value as any;
}

export function CHILDDOCUMENTTYPEToJSONTyped(value: any, ignoreDiscriminator: boolean): CHILDDOCUMENTTYPE {
    return value as CHILDDOCUMENTTYPE;
}

