/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const CHILDCONDITIONKEY = {
    HasDisability: 'has_disability'
} as const;
export type CHILDCONDITIONKEY = typeof CHILDCONDITIONKEY[keyof typeof CHILDCONDITIONKEY];


export function instanceOfCHILDCONDITIONKEY(value: any): boolean {
    for (const key in CHILDCONDITIONKEY) {
        if (Object.prototype.hasOwnProperty.call(CHILDCONDITIONKEY, key)) {
            if (CHILDCONDITIONKEY[key as keyof typeof CHILDCONDITIONKEY] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CHILDCONDITIONKEYFromJSON(json: any): CHILDCONDITIONKEY {
    return CHILDCONDITIONKEYFromJSONTyped(json, false);
}

export function CHILDCONDITIONKEYFromJSONTyped(json: any, ignoreDiscriminator: boolean): CHILDCONDITIONKEY {
    return json as CHILDCONDITIONKEY;
}

export function CHILDCONDITIONKEYToJSON(value?: CHILDCONDITIONKEY | null): any {
    return value as any;
}

export function CHILDCONDITIONKEYToJSONTyped(value: any, ignoreDiscriminator: boolean): CHILDCONDITIONKEY {
    return value as CHILDCONDITIONKEY;
}

