/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const CONDITIONKEY = {
    IsEmployed: 'is_employed',
    IsSelfEmployed: 'is_self_employed',
    IsStudent: 'is_student',
    FiledTaxInDesiredLocation: 'filed_tax_in_desired_location',
    ResidesInDesiredLocation: 'resides_in_desired_location'
} as const;
export type CONDITIONKEY = typeof CONDITIONKEY[keyof typeof CONDITIONKEY];


export function instanceOfCONDITIONKEY(value: any): boolean {
    for (const key in CONDITIONKEY) {
        if (Object.prototype.hasOwnProperty.call(CONDITIONKEY, key)) {
            if (CONDITIONKEY[key as keyof typeof CONDITIONKEY] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CONDITIONKEYFromJSON(json: any): CONDITIONKEY {
    return CONDITIONKEYFromJSONTyped(json, false);
}

export function CONDITIONKEYFromJSONTyped(json: any, ignoreDiscriminator: boolean): CONDITIONKEY {
    return json as CONDITIONKEY;
}

export function CONDITIONKEYToJSON(value?: CONDITIONKEY | null): any {
    return value as any;
}

export function CONDITIONKEYToJSONTyped(value: any, ignoreDiscriminator: boolean): CONDITIONKEY {
    return value as CONDITIONKEY;
}

