/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const DOCUMENTTYPE = {
    EmploymentProof: 'employment_proof',
    SelfEmploymentProof: 'self_employment_proof',
    StudentProof: 'student_proof',
    FiledTaxInDesiredLocationProof: 'filed_tax_in_desired_location_proof',
    ResidesInDesiredLocationProof: 'resides_in_desired_location_proof'
} as const;
export type DOCUMENTTYPE = typeof DOCUMENTTYPE[keyof typeof DOCUMENTTYPE];


export function instanceOfDOCUMENTTYPE(value: any): boolean {
    for (const key in DOCUMENTTYPE) {
        if (Object.prototype.hasOwnProperty.call(DOCUMENTTYPE, key)) {
            if (DOCUMENTTYPE[key as keyof typeof DOCUMENTTYPE] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DOCUMENTTYPEFromJSON(json: any): DOCUMENTTYPE {
    return DOCUMENTTYPEFromJSONTyped(json, false);
}

export function DOCUMENTTYPEFromJSONTyped(json: any, ignoreDiscriminator: boolean): DOCUMENTTYPE {
    return json as DOCUMENTTYPE;
}

export function DOCUMENTTYPEToJSON(value?: DOCUMENTTYPE | null): any {
    return value as any;
}

export function DOCUMENTTYPEToJSONTyped(value: any, ignoreDiscriminator: boolean): DOCUMENTTYPE {
    return value as DOCUMENTTYPE;
}

