/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HTTPError
 */
export interface HTTPError {
    /**
     * 
     * @type {number}
     * @memberof HTTPError
     */
    code: number;
    /**
     * 
     * @type {string}
     * @memberof HTTPError
     */
    message: string;
}

/**
 * Check if a given object implements the HTTPError interface.
 */
export function instanceOfHTTPError(value: object): value is HTTPError {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function HTTPErrorFromJSON(json: any): HTTPError {
    return HTTPErrorFromJSONTyped(json, false);
}

export function HTTPErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): HTTPError {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'message': json['message'],
    };
}

export function HTTPErrorToJSON(json: any): HTTPError {
    return HTTPErrorToJSONTyped(json, false);
}

export function HTTPErrorToJSONTyped(value?: HTTPError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
    };
}

