/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PropertyParentDocument } from './PropertyParentDocument';
import {
    PropertyParentDocumentFromJSON,
    PropertyParentDocumentFromJSONTyped,
    PropertyParentDocumentToJSON,
    PropertyParentDocumentToJSONTyped,
} from './PropertyParentDocument';

/**
 * 
 * @export
 * @interface PagedResponsePropertyParentDocument
 */
export interface PagedResponsePropertyParentDocument {
    /**
     * 
     * @type {Array<PropertyParentDocument>}
     * @memberof PagedResponsePropertyParentDocument
     */
    items: Array<PropertyParentDocument>;
    /**
     * 
     * @type {number}
     * @memberof PagedResponsePropertyParentDocument
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof PagedResponsePropertyParentDocument
     */
    pageNumber: number;
    /**
     * 
     * @type {number}
     * @memberof PagedResponsePropertyParentDocument
     */
    pageSize: number;
    /**
     * 
     * @type {boolean}
     * @memberof PagedResponsePropertyParentDocument
     */
    hasNextPage: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PagedResponsePropertyParentDocument
     */
    hasPreviousPage: boolean;
    /**
     * 
     * @type {number}
     * @memberof PagedResponsePropertyParentDocument
     */
    totalPages: number;
}

/**
 * Check if a given object implements the PagedResponsePropertyParentDocument interface.
 */
export function instanceOfPagedResponsePropertyParentDocument(value: object): value is PagedResponsePropertyParentDocument {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('pageNumber' in value) || value['pageNumber'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('hasNextPage' in value) || value['hasNextPage'] === undefined) return false;
    if (!('hasPreviousPage' in value) || value['hasPreviousPage'] === undefined) return false;
    if (!('totalPages' in value) || value['totalPages'] === undefined) return false;
    return true;
}

export function PagedResponsePropertyParentDocumentFromJSON(json: any): PagedResponsePropertyParentDocument {
    return PagedResponsePropertyParentDocumentFromJSONTyped(json, false);
}

export function PagedResponsePropertyParentDocumentFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedResponsePropertyParentDocument {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(PropertyParentDocumentFromJSON)),
        'total': json['total'],
        'pageNumber': json['page_number'],
        'pageSize': json['page_size'],
        'hasNextPage': json['has_next_page'],
        'hasPreviousPage': json['has_previous_page'],
        'totalPages': json['total_pages'],
    };
}

export function PagedResponsePropertyParentDocumentToJSON(json: any): PagedResponsePropertyParentDocument {
    return PagedResponsePropertyParentDocumentToJSONTyped(json, false);
}

export function PagedResponsePropertyParentDocumentToJSONTyped(value?: PagedResponsePropertyParentDocument | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(PropertyParentDocumentToJSON)),
        'total': value['total'],
        'page_number': value['pageNumber'],
        'page_size': value['pageSize'],
        'has_next_page': value['hasNextPage'],
        'has_previous_page': value['hasPreviousPage'],
        'total_pages': value['totalPages'],
    };
}

