/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PropertyChild } from './PropertyChild';
import {
    PropertyChildFromJSON,
    PropertyChildFromJSONTyped,
    PropertyChildToJSON,
    PropertyChildToJSONTyped,
} from './PropertyChild';

/**
 * 
 * @export
 * @interface PagedResponsePropertyChild
 */
export interface PagedResponsePropertyChild {
    /**
     * 
     * @type {Array<PropertyChild>}
     * @memberof PagedResponsePropertyChild
     */
    items: Array<PropertyChild>;
    /**
     * 
     * @type {number}
     * @memberof PagedResponsePropertyChild
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof PagedResponsePropertyChild
     */
    pageNumber: number;
    /**
     * 
     * @type {number}
     * @memberof PagedResponsePropertyChild
     */
    pageSize: number;
    /**
     * 
     * @type {boolean}
     * @memberof PagedResponsePropertyChild
     */
    hasNextPage: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PagedResponsePropertyChild
     */
    hasPreviousPage: boolean;
    /**
     * 
     * @type {number}
     * @memberof PagedResponsePropertyChild
     */
    totalPages: number;
}

/**
 * Check if a given object implements the PagedResponsePropertyChild interface.
 */
export function instanceOfPagedResponsePropertyChild(value: object): value is PagedResponsePropertyChild {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('pageNumber' in value) || value['pageNumber'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('hasNextPage' in value) || value['hasNextPage'] === undefined) return false;
    if (!('hasPreviousPage' in value) || value['hasPreviousPage'] === undefined) return false;
    if (!('totalPages' in value) || value['totalPages'] === undefined) return false;
    return true;
}

export function PagedResponsePropertyChildFromJSON(json: any): PagedResponsePropertyChild {
    return PagedResponsePropertyChildFromJSONTyped(json, false);
}

export function PagedResponsePropertyChildFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedResponsePropertyChild {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(PropertyChildFromJSON)),
        'total': json['total'],
        'pageNumber': json['page_number'],
        'pageSize': json['page_size'],
        'hasNextPage': json['has_next_page'],
        'hasPreviousPage': json['has_previous_page'],
        'totalPages': json['total_pages'],
    };
}

export function PagedResponsePropertyChildToJSON(json: any): PagedResponsePropertyChild {
    return PagedResponsePropertyChildToJSONTyped(json, false);
}

export function PagedResponsePropertyChildToJSONTyped(value?: PagedResponsePropertyChild | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(PropertyChildToJSON)),
        'total': value['total'],
        'page_number': value['pageNumber'],
        'page_size': value['pageSize'],
        'has_next_page': value['hasNextPage'],
        'has_previous_page': value['hasPreviousPage'],
        'total_pages': value['totalPages'],
    };
}

