/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Property } from './Property';
import {
    PropertyFromJSON,
    PropertyFromJSONTyped,
    PropertyToJSON,
    PropertyToJSONTyped,
} from './Property';

/**
 * 
 * @export
 * @interface PagedResponseProperty
 */
export interface PagedResponseProperty {
    /**
     * 
     * @type {Array<Property>}
     * @memberof PagedResponseProperty
     */
    items: Array<Property>;
    /**
     * 
     * @type {number}
     * @memberof PagedResponseProperty
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof PagedResponseProperty
     */
    pageNumber: number;
    /**
     * 
     * @type {number}
     * @memberof PagedResponseProperty
     */
    pageSize: number;
    /**
     * 
     * @type {boolean}
     * @memberof PagedResponseProperty
     */
    hasNextPage: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PagedResponseProperty
     */
    hasPreviousPage: boolean;
    /**
     * 
     * @type {number}
     * @memberof PagedResponseProperty
     */
    totalPages: number;
}

/**
 * Check if a given object implements the PagedResponseProperty interface.
 */
export function instanceOfPagedResponseProperty(value: object): value is PagedResponseProperty {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('pageNumber' in value) || value['pageNumber'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('hasNextPage' in value) || value['hasNextPage'] === undefined) return false;
    if (!('hasPreviousPage' in value) || value['hasPreviousPage'] === undefined) return false;
    if (!('totalPages' in value) || value['totalPages'] === undefined) return false;
    return true;
}

export function PagedResponsePropertyFromJSON(json: any): PagedResponseProperty {
    return PagedResponsePropertyFromJSONTyped(json, false);
}

export function PagedResponsePropertyFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedResponseProperty {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(PropertyFromJSON)),
        'total': json['total'],
        'pageNumber': json['page_number'],
        'pageSize': json['page_size'],
        'hasNextPage': json['has_next_page'],
        'hasPreviousPage': json['has_previous_page'],
        'totalPages': json['total_pages'],
    };
}

export function PagedResponsePropertyToJSON(json: any): PagedResponseProperty {
    return PagedResponsePropertyToJSONTyped(json, false);
}

export function PagedResponsePropertyToJSONTyped(value?: PagedResponseProperty | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(PropertyToJSON)),
        'total': value['total'],
        'page_number': value['pageNumber'],
        'page_size': value['pageSize'],
        'has_next_page': value['hasNextPage'],
        'has_previous_page': value['hasPreviousPage'],
        'total_pages': value['totalPages'],
    };
}

