/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DOCUMENTTYPE } from './DOCUMENTTYPE';
import {
    DOCUMENTTYPEFromJSON,
    DOCUMENTTYPEFromJSONTyped,
    DOCUMENTTYPEToJSON,
    DOCUMENTTYPEToJSONTyped,
} from './DOCUMENTTYPE';

/**
 * 
 * @export
 * @interface ParentDocument
 */
export interface ParentDocument {
    /**
     * 
     * @type {string}
     * @memberof ParentDocument
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ParentDocument
     */
    userId: string;
    /**
     * 
     * @type {DOCUMENTTYPE}
     * @memberof ParentDocument
     */
    documentType: DOCUMENTTYPE;
    /**
     * 
     * @type {string}
     * @memberof ParentDocument
     */
    filePath: string;
}



/**
 * Check if a given object implements the ParentDocument interface.
 */
export function instanceOfParentDocument(value: object): value is ParentDocument {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('documentType' in value) || value['documentType'] === undefined) return false;
    if (!('filePath' in value) || value['filePath'] === undefined) return false;
    return true;
}

export function ParentDocumentFromJSON(json: any): ParentDocument {
    return ParentDocumentFromJSONTyped(json, false);
}

export function ParentDocumentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ParentDocument {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'userId': json['user_id'],
        'documentType': DOCUMENTTYPEFromJSON(json['document_type']),
        'filePath': json['file_path'],
    };
}

export function ParentDocumentToJSON(json: any): ParentDocument {
    return ParentDocumentToJSONTyped(json, false);
}

export function ParentDocumentToJSONTyped(value?: ParentDocument | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'user_id': value['userId'],
        'document_type': DOCUMENTTYPEToJSON(value['documentType']),
        'file_path': value['filePath'],
    };
}

