/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PROPERTYUSERROLE } from './PROPERTYUSERROLE';
import {
    PROPERTYUSERROLEFromJSON,
    PROPERTYUSERROLEFromJSONTyped,
    PROPERTYUSERROLEToJSON,
    PROPERTYUSERROLEToJSONTyped,
} from './PROPERTYUSERROLE';

/**
 * 
 * @export
 * @interface PropertyUser
 */
export interface PropertyUser {
    /**
     * 
     * @type {string}
     * @memberof PropertyUser
     */
    propertyId: string;
    /**
     * 
     * @type {string}
     * @memberof PropertyUser
     */
    userId: string;
    /**
     * 
     * @type {PROPERTYUSERROLE}
     * @memberof PropertyUser
     */
    role: PROPERTYUSERROLE;
}



/**
 * Check if a given object implements the PropertyUser interface.
 */
export function instanceOfPropertyUser(value: object): value is PropertyUser {
    if (!('propertyId' in value) || value['propertyId'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    return true;
}

export function PropertyUserFromJSON(json: any): PropertyUser {
    return PropertyUserFromJSONTyped(json, false);
}

export function PropertyUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): PropertyUser {
    if (json == null) {
        return json;
    }
    return {
        
        'propertyId': json['property_id'],
        'userId': json['user_id'],
        'role': PROPERTYUSERROLEFromJSON(json['role']),
    };
}

export function PropertyUserToJSON(json: any): PropertyUser {
    return PropertyUserToJSONTyped(json, false);
}

export function PropertyUserToJSONTyped(value?: PropertyUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'property_id': value['propertyId'],
        'user_id': value['userId'],
        'role': PROPERTYUSERROLEToJSON(value['role']),
    };
}

