/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PropertyChild
 */
export interface PropertyChild {
    /**
     * 
     * @type {string}
     * @memberof PropertyChild
     */
    propertyId: string;
    /**
     * 
     * @type {string}
     * @memberof PropertyChild
     */
    childId: string;
    /**
     * 
     * @type {number}
     * @memberof PropertyChild
     */
    points: number;
    /**
     * 
     * @type {boolean}
     * @memberof PropertyChild
     */
    approved: boolean;
}

/**
 * Check if a given object implements the PropertyChild interface.
 */
export function instanceOfPropertyChild(value: object): value is PropertyChild {
    if (!('propertyId' in value) || value['propertyId'] === undefined) return false;
    if (!('childId' in value) || value['childId'] === undefined) return false;
    if (!('points' in value) || value['points'] === undefined) return false;
    if (!('approved' in value) || value['approved'] === undefined) return false;
    return true;
}

export function PropertyChildFromJSON(json: any): PropertyChild {
    return PropertyChildFromJSONTyped(json, false);
}

export function PropertyChildFromJSONTyped(json: any, ignoreDiscriminator: boolean): PropertyChild {
    if (json == null) {
        return json;
    }
    return {
        
        'propertyId': json['property_id'],
        'childId': json['child_id'],
        'points': json['points'],
        'approved': json['approved'],
    };
}

export function PropertyChildToJSON(json: any): PropertyChild {
    return PropertyChildToJSONTyped(json, false);
}

export function PropertyChildToJSONTyped(value?: PropertyChild | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'property_id': value['propertyId'],
        'child_id': value['childId'],
        'points': value['points'],
        'approved': value['approved'],
    };
}

