/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { REQUESTSTATUS } from './REQUESTSTATUS';
import {
    REQUESTSTATUSFromJSON,
    REQUESTSTATUSFromJSONTyped,
    REQUESTSTATUSToJSON,
    REQUESTSTATUSToJSONTyped,
} from './REQUESTSTATUS';

/**
 * 
 * @export
 * @interface PropertyParentDocument
 */
export interface PropertyParentDocument {
    /**
     * 
     * @type {string}
     * @memberof PropertyParentDocument
     */
    propertyId: string;
    /**
     * 
     * @type {string}
     * @memberof PropertyParentDocument
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof PropertyParentDocument
     */
    parentDocumentId: string;
    /**
     * 
     * @type {REQUESTSTATUS}
     * @memberof PropertyParentDocument
     */
    requestStatus: REQUESTSTATUS;
    /**
     * 
     * @type {string}
     * @memberof PropertyParentDocument
     */
    approvedBy: string | null;
}



/**
 * Check if a given object implements the PropertyParentDocument interface.
 */
export function instanceOfPropertyParentDocument(value: object): value is PropertyParentDocument {
    if (!('propertyId' in value) || value['propertyId'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('parentDocumentId' in value) || value['parentDocumentId'] === undefined) return false;
    if (!('requestStatus' in value) || value['requestStatus'] === undefined) return false;
    if (!('approvedBy' in value) || value['approvedBy'] === undefined) return false;
    return true;
}

export function PropertyParentDocumentFromJSON(json: any): PropertyParentDocument {
    return PropertyParentDocumentFromJSONTyped(json, false);
}

export function PropertyParentDocumentFromJSONTyped(json: any, ignoreDiscriminator: boolean): PropertyParentDocument {
    if (json == null) {
        return json;
    }
    return {
        
        'propertyId': json['property_id'],
        'userId': json['user_id'],
        'parentDocumentId': json['parent_document_id'],
        'requestStatus': REQUESTSTATUSFromJSON(json['request_status']),
        'approvedBy': json['approved_by'],
    };
}

export function PropertyParentDocumentToJSON(json: any): PropertyParentDocument {
    return PropertyParentDocumentToJSONTyped(json, false);
}

export function PropertyParentDocumentToJSONTyped(value?: PropertyParentDocument | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'property_id': value['propertyId'],
        'user_id': value['userId'],
        'parent_document_id': value['parentDocumentId'],
        'request_status': REQUESTSTATUSToJSON(value['requestStatus']),
        'approved_by': value['approvedBy'],
    };
}

