/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { REQUESTSTATUS } from './REQUESTSTATUS';
import {
    REQUESTSTATUSFromJSON,
    REQUESTSTATUSFromJSONTyped,
    REQUESTSTATUSToJSON,
    REQUESTSTATUSToJSONTyped,
} from './REQUESTSTATUS';

/**
 * 
 * @export
 * @interface PropertyChildDocument
 */
export interface PropertyChildDocument {
    /**
     * 
     * @type {string}
     * @memberof PropertyChildDocument
     */
    propertyId: string;
    /**
     * 
     * @type {string}
     * @memberof PropertyChildDocument
     */
    childId: string;
    /**
     * 
     * @type {string}
     * @memberof PropertyChildDocument
     */
    childDocumentId: string;
    /**
     * 
     * @type {REQUESTSTATUS}
     * @memberof PropertyChildDocument
     */
    requestStatus: REQUESTSTATUS;
    /**
     * 
     * @type {string}
     * @memberof PropertyChildDocument
     */
    approvedBy: string | null;
}



/**
 * Check if a given object implements the PropertyChildDocument interface.
 */
export function instanceOfPropertyChildDocument(value: object): value is PropertyChildDocument {
    if (!('propertyId' in value) || value['propertyId'] === undefined) return false;
    if (!('childId' in value) || value['childId'] === undefined) return false;
    if (!('childDocumentId' in value) || value['childDocumentId'] === undefined) return false;
    if (!('requestStatus' in value) || value['requestStatus'] === undefined) return false;
    if (!('approvedBy' in value) || value['approvedBy'] === undefined) return false;
    return true;
}

export function PropertyChildDocumentFromJSON(json: any): PropertyChildDocument {
    return PropertyChildDocumentFromJSONTyped(json, false);
}

export function PropertyChildDocumentFromJSONTyped(json: any, ignoreDiscriminator: boolean): PropertyChildDocument {
    if (json == null) {
        return json;
    }
    return {
        
        'propertyId': json['property_id'],
        'childId': json['child_id'],
        'childDocumentId': json['child_document_id'],
        'requestStatus': REQUESTSTATUSFromJSON(json['request_status']),
        'approvedBy': json['approved_by'],
    };
}

export function PropertyChildDocumentToJSON(json: any): PropertyChildDocument {
    return PropertyChildDocumentToJSONTyped(json, false);
}

export function PropertyChildDocumentToJSONTyped(value?: PropertyChildDocument | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'property_id': value['propertyId'],
        'child_id': value['childId'],
        'child_document_id': value['childDocumentId'],
        'request_status': REQUESTSTATUSToJSON(value['requestStatus']),
        'approved_by': value['approvedBy'],
    };
}

