/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CONDITIONKEY } from './CONDITIONKEY';
import {
    CONDITIONKEYFromJSON,
    CONDITIONKEYFromJSONTyped,
    CONDITIONKEYToJSON,
    CONDITIONKEYToJSONTyped,
} from './CONDITIONKEY';
import type { REQUIREMENTTYPE } from './REQUIREMENTTYPE';
import {
    REQUIREMENTTYPEFromJSON,
    REQUIREMENTTYPEFromJSONTyped,
    REQUIREMENTTYPEToJSON,
    REQUIREMENTTYPEToJSONTyped,
} from './REQUIREMENTTYPE';
import type { DOCUMENTTYPE } from './DOCUMENTTYPE';
import {
    DOCUMENTTYPEFromJSON,
    DOCUMENTTYPEFromJSONTyped,
    DOCUMENTTYPEToJSON,
    DOCUMENTTYPEToJSONTyped,
} from './DOCUMENTTYPE';

/**
 * 
 * @export
 * @interface PropertyParentDocumentRequirement
 */
export interface PropertyParentDocumentRequirement {
    /**
     * 
     * @type {string}
     * @memberof PropertyParentDocumentRequirement
     */
    propertyId: string;
    /**
     * 
     * @type {DOCUMENTTYPE}
     * @memberof PropertyParentDocumentRequirement
     */
    documentType: DOCUMENTTYPE;
    /**
     * 
     * @type {REQUIREMENTTYPE}
     * @memberof PropertyParentDocumentRequirement
     */
    requirementType: REQUIREMENTTYPE;
    /**
     * 
     * @type {CONDITIONKEY}
     * @memberof PropertyParentDocumentRequirement
     */
    conditionKey: CONDITIONKEY;
    /**
     * 
     * @type {number}
     * @memberof PropertyParentDocumentRequirement
     */
    pointValue: number;
}



/**
 * Check if a given object implements the PropertyParentDocumentRequirement interface.
 */
export function instanceOfPropertyParentDocumentRequirement(value: object): value is PropertyParentDocumentRequirement {
    if (!('propertyId' in value) || value['propertyId'] === undefined) return false;
    if (!('documentType' in value) || value['documentType'] === undefined) return false;
    if (!('requirementType' in value) || value['requirementType'] === undefined) return false;
    if (!('conditionKey' in value) || value['conditionKey'] === undefined) return false;
    if (!('pointValue' in value) || value['pointValue'] === undefined) return false;
    return true;
}

export function PropertyParentDocumentRequirementFromJSON(json: any): PropertyParentDocumentRequirement {
    return PropertyParentDocumentRequirementFromJSONTyped(json, false);
}

export function PropertyParentDocumentRequirementFromJSONTyped(json: any, ignoreDiscriminator: boolean): PropertyParentDocumentRequirement {
    if (json == null) {
        return json;
    }
    return {
        
        'propertyId': json['property_id'],
        'documentType': DOCUMENTTYPEFromJSON(json['document_type']),
        'requirementType': REQUIREMENTTYPEFromJSON(json['requirement_type']),
        'conditionKey': CONDITIONKEYFromJSON(json['condition_key']),
        'pointValue': json['point_value'],
    };
}

export function PropertyParentDocumentRequirementToJSON(json: any): PropertyParentDocumentRequirement {
    return PropertyParentDocumentRequirementToJSONTyped(json, false);
}

export function PropertyParentDocumentRequirementToJSONTyped(value?: PropertyParentDocumentRequirement | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'property_id': value['propertyId'],
        'document_type': DOCUMENTTYPEToJSON(value['documentType']),
        'requirement_type': REQUIREMENTTYPEToJSON(value['requirementType']),
        'condition_key': CONDITIONKEYToJSON(value['conditionKey']),
        'point_value': value['pointValue'],
    };
}

