/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CHILDDOCUMENTTYPE } from './CHILDDOCUMENTTYPE';
import {
    CHILDDOCUMENTTYPEFromJSON,
    CHILDDOCUMENTTYPEFromJSONTyped,
    CHILDDOCUMENTTYPEToJSON,
    CHILDDOCUMENTTYPEToJSONTyped,
} from './CHILDDOCUMENTTYPE';
import type { CHILDCONDITIONKEY } from './CHILDCONDITIONKEY';
import {
    CHILDCONDITIONKEYFromJSON,
    CHILDCONDITIONKEYFromJSONTyped,
    CHILDCONDITIONKEYToJSON,
    CHILDCONDITIONKEYToJSONTyped,
} from './CHILDCONDITIONKEY';
import type { REQUIREMENTTYPE } from './REQUIREMENTTYPE';
import {
    REQUIREMENTTYPEFromJSON,
    REQUIREMENTTYPEFromJSONTyped,
    REQUIREMENTTYPEToJSON,
    REQUIREMENTTYPEToJSONTyped,
} from './REQUIREMENTTYPE';

/**
 * 
 * @export
 * @interface PropertyChildDocumentRequirement
 */
export interface PropertyChildDocumentRequirement {
    /**
     * 
     * @type {string}
     * @memberof PropertyChildDocumentRequirement
     */
    propertyId: string;
    /**
     * 
     * @type {CHILDDOCUMENTTYPE}
     * @memberof PropertyChildDocumentRequirement
     */
    documentType: CHILDDOCUMENTTYPE;
    /**
     * 
     * @type {REQUIREMENTTYPE}
     * @memberof PropertyChildDocumentRequirement
     */
    requirementType: REQUIREMENTTYPE;
    /**
     * 
     * @type {CHILDCONDITIONKEY}
     * @memberof PropertyChildDocumentRequirement
     */
    conditionKey: CHILDCONDITIONKEY;
    /**
     * 
     * @type {number}
     * @memberof PropertyChildDocumentRequirement
     */
    pointValue: number;
}



/**
 * Check if a given object implements the PropertyChildDocumentRequirement interface.
 */
export function instanceOfPropertyChildDocumentRequirement(value: object): value is PropertyChildDocumentRequirement {
    if (!('propertyId' in value) || value['propertyId'] === undefined) return false;
    if (!('documentType' in value) || value['documentType'] === undefined) return false;
    if (!('requirementType' in value) || value['requirementType'] === undefined) return false;
    if (!('conditionKey' in value) || value['conditionKey'] === undefined) return false;
    if (!('pointValue' in value) || value['pointValue'] === undefined) return false;
    return true;
}

export function PropertyChildDocumentRequirementFromJSON(json: any): PropertyChildDocumentRequirement {
    return PropertyChildDocumentRequirementFromJSONTyped(json, false);
}

export function PropertyChildDocumentRequirementFromJSONTyped(json: any, ignoreDiscriminator: boolean): PropertyChildDocumentRequirement {
    if (json == null) {
        return json;
    }
    return {
        
        'propertyId': json['property_id'],
        'documentType': CHILDDOCUMENTTYPEFromJSON(json['document_type']),
        'requirementType': REQUIREMENTTYPEFromJSON(json['requirement_type']),
        'conditionKey': CHILDCONDITIONKEYFromJSON(json['condition_key']),
        'pointValue': json['point_value'],
    };
}

export function PropertyChildDocumentRequirementToJSON(json: any): PropertyChildDocumentRequirement {
    return PropertyChildDocumentRequirementToJSONTyped(json, false);
}

export function PropertyChildDocumentRequirementToJSONTyped(value?: PropertyChildDocumentRequirement | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'property_id': value['propertyId'],
        'document_type': CHILDDOCUMENTTYPEToJSON(value['documentType']),
        'requirement_type': REQUIREMENTTYPEToJSON(value['requirementType']),
        'condition_key': CHILDCONDITIONKEYToJSON(value['conditionKey']),
        'point_value': value['pointValue'],
    };
}

