/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PROPERTYUSERROLE = {
    Admin: 'admin',
    Parent: 'parent'
} as const;
export type PROPERTYUSERROLE = typeof PROPERTYUSERROLE[keyof typeof PROPERTYUSERROLE];


export function instanceOfPROPERTYUSERROLE(value: any): boolean {
    for (const key in PROPERTYUSERROLE) {
        if (Object.prototype.hasOwnProperty.call(PROPERTYUSERROLE, key)) {
            if (PROPERTYUSERROLE[key as keyof typeof PROPERTYUSERROLE] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PROPERTYUSERROLEFromJSON(json: any): PROPERTYUSERROLE {
    return PROPERTYUSERROLEFromJSONTyped(json, false);
}

export function PROPERTYUSERROLEFromJSONTyped(json: any, ignoreDiscriminator: boolean): PROPERTYUSERROLE {
    return json as PROPERTYUSERROLE;
}

export function PROPERTYUSERROLEToJSON(value?: PROPERTYUSERROLE | null): any {
    return value as any;
}

export function PROPERTYUSERROLEToJSONTyped(value: any, ignoreDiscriminator: boolean): PROPERTYUSERROLE {
    return value as PROPERTYUSERROLE;
}

