/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const REQUIREMENTTYPE = {
    Always: 'always',
    Conditional: 'conditional'
} as const;
export type REQUIREMENTTYPE = typeof REQUIREMENTTYPE[keyof typeof REQUIREMENTTYPE];


export function instanceOfREQUIREMENTTYPE(value: any): boolean {
    for (const key in REQUIREMENTTYPE) {
        if (Object.prototype.hasOwnProperty.call(REQUIREMENTTYPE, key)) {
            if (REQUIREMENTTYPE[key as keyof typeof REQUIREMENTTYPE] === value) {
                return true;
            }
        }
    }
    return false;
}

export function REQUIREMENTTYPEFromJSON(json: any): REQUIREMENTTYPE {
    return REQUIREMENTTYPEFromJSONTyped(json, false);
}

export function REQUIREMENTTYPEFromJSONTyped(json: any, ignoreDiscriminator: boolean): REQUIREMENTTYPE {
    return json as REQUIREMENTTYPE;
}

export function REQUIREMENTTYPEToJSON(value?: REQUIREMENTTYPE | null): any {
    return value as any;
}

export function REQUIREMENTTYPEToJSONTyped(value: any, ignoreDiscriminator: boolean): REQUIREMENTTYPE {
    return value as REQUIREMENTTYPE;
}

