/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const REQUESTSTATUS = {
    Pending: 'pending',
    Approved: 'approved',
    Rejected: 'rejected'
} as const;
export type REQUESTSTATUS = typeof REQUESTSTATUS[keyof typeof REQUESTSTATUS];


export function instanceOfREQUESTSTATUS(value: any): boolean {
    for (const key in REQUESTSTATUS) {
        if (Object.prototype.hasOwnProperty.call(REQUESTSTATUS, key)) {
            if (REQUESTSTATUS[key as keyof typeof REQUESTSTATUS] === value) {
                return true;
            }
        }
    }
    return false;
}

export function REQUESTSTATUSFromJSON(json: any): REQUESTSTATUS {
    return REQUESTSTATUSFromJSONTyped(json, false);
}

export function REQUESTSTATUSFromJSONTyped(json: any, ignoreDiscriminator: boolean): REQUESTSTATUS {
    return json as REQUESTSTATUS;
}

export function REQUESTSTATUSToJSON(value?: REQUESTSTATUS | null): any {
    return value as any;
}

export function REQUESTSTATUSToJSONTyped(value: any, ignoreDiscriminator: boolean): REQUESTSTATUS {
    return value as REQUESTSTATUS;
}

