/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiResponseListPropertyChildDocument,
  ApiResponseListPropertyParentDocument,
  ApiResponsePagedResponsePropertyParentDocument,
  ApiResponsePropertyParentDocument,
  HTTPValidationError,
  REQUESTSTATUS,
} from '../models/index';
import {
    ApiResponseListPropertyChildDocumentFromJSON,
    ApiResponseListPropertyChildDocumentToJSON,
    ApiResponseListPropertyParentDocumentFromJSON,
    ApiResponseListPropertyParentDocumentToJSON,
    ApiResponsePagedResponsePropertyParentDocumentFromJSON,
    ApiResponsePagedResponsePropertyParentDocumentToJSON,
    ApiResponsePropertyParentDocumentFromJSON,
    ApiResponsePropertyParentDocumentToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    REQUESTSTATUSFromJSON,
    REQUESTSTATUSToJSON,
} from '../models/index';

export interface GetAllDocumentApprovalRequestsForGivenPropertyChildPropertiesPropertyIdChildrenChildIdChildDocumentRequestsGetRequest {
    propertyId: string;
    childId: string;
}

export interface GetAllDocumentApprovalRequestsForGivenPropertyPropertiesPropertyIdParentDocumentRequestsGetRequest {
    propertyId: string;
    pageSize?: number;
    pageNumber?: number;
}

export interface GetPropertiesPropertiesPropertyIdParentsParentIdParentDocumentRequestsGetRequest {
    propertyId: string;
    parentId: string;
}

export interface GetPropertyParentDocumentApprovalRequestByDocumentIdPropertiesPropertyIdParentsParentIdParentDocumentsParentDocIdGetRequest {
    propertyId: string;
    parentId: string;
    parentDocId: string;
}

export interface SendPropertyParentDocumentApprovalRequestPropertiesPropertyIdParentsParentIdParentDocumentsParentDocIdPostRequest {
    propertyId: string;
    parentId: string;
    parentDocId: string;
}

export interface SthPropertiesPropertyIdParentsParentIdParentDocumentsParentDocumentIdStatusRequestStatusPatchRequest {
    propertyId: string;
    parentId: string;
    parentDocumentId: string;
    requestStatus: REQUESTSTATUS;
}

/**
 * 
 */
export class ComplianceApi extends runtime.BaseAPI {

    /**
     * Get All Document Approval Requests For Given Property Child
     */
    async getAllDocumentApprovalRequestsForGivenPropertyChildPropertiesPropertyIdChildrenChildIdChildDocumentRequestsGetRaw(requestParameters: GetAllDocumentApprovalRequestsForGivenPropertyChildPropertiesPropertyIdChildrenChildIdChildDocumentRequestsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseListPropertyChildDocument>> {
        if (requestParameters['propertyId'] == null) {
            throw new runtime.RequiredError(
                'propertyId',
                'Required parameter "propertyId" was null or undefined when calling getAllDocumentApprovalRequestsForGivenPropertyChildPropertiesPropertyIdChildrenChildIdChildDocumentRequestsGet().'
            );
        }

        if (requestParameters['childId'] == null) {
            throw new runtime.RequiredError(
                'childId',
                'Required parameter "childId" was null or undefined when calling getAllDocumentApprovalRequestsForGivenPropertyChildPropertiesPropertyIdChildrenChildIdChildDocumentRequestsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/properties/{property_id}/children/{child_id}/child-document-requests`;
        urlPath = urlPath.replace(`{${"property_id"}}`, encodeURIComponent(String(requestParameters['propertyId'])));
        urlPath = urlPath.replace(`{${"child_id"}}`, encodeURIComponent(String(requestParameters['childId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiResponseListPropertyChildDocumentFromJSON(jsonValue));
    }

    /**
     * Get All Document Approval Requests For Given Property Child
     */
    async getAllDocumentApprovalRequestsForGivenPropertyChildPropertiesPropertyIdChildrenChildIdChildDocumentRequestsGet(requestParameters: GetAllDocumentApprovalRequestsForGivenPropertyChildPropertiesPropertyIdChildrenChildIdChildDocumentRequestsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseListPropertyChildDocument> {
        const response = await this.getAllDocumentApprovalRequestsForGivenPropertyChildPropertiesPropertyIdChildrenChildIdChildDocumentRequestsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get All Document Approval Requests For Given Property
     */
    async getAllDocumentApprovalRequestsForGivenPropertyPropertiesPropertyIdParentDocumentRequestsGetRaw(requestParameters: GetAllDocumentApprovalRequestsForGivenPropertyPropertiesPropertyIdParentDocumentRequestsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponsePagedResponsePropertyParentDocument>> {
        if (requestParameters['propertyId'] == null) {
            throw new runtime.RequiredError(
                'propertyId',
                'Required parameter "propertyId" was null or undefined when calling getAllDocumentApprovalRequestsForGivenPropertyPropertiesPropertyIdParentDocumentRequestsGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['pageSize'] != null) {
            queryParameters['page_size'] = requestParameters['pageSize'];
        }

        if (requestParameters['pageNumber'] != null) {
            queryParameters['page_number'] = requestParameters['pageNumber'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/properties/{property_id}/parent-document-requests`;
        urlPath = urlPath.replace(`{${"property_id"}}`, encodeURIComponent(String(requestParameters['propertyId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiResponsePagedResponsePropertyParentDocumentFromJSON(jsonValue));
    }

    /**
     * Get All Document Approval Requests For Given Property
     */
    async getAllDocumentApprovalRequestsForGivenPropertyPropertiesPropertyIdParentDocumentRequestsGet(requestParameters: GetAllDocumentApprovalRequestsForGivenPropertyPropertiesPropertyIdParentDocumentRequestsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponsePagedResponsePropertyParentDocument> {
        const response = await this.getAllDocumentApprovalRequestsForGivenPropertyPropertiesPropertyIdParentDocumentRequestsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Properties
     */
    async getPropertiesPropertiesPropertyIdParentsParentIdParentDocumentRequestsGetRaw(requestParameters: GetPropertiesPropertiesPropertyIdParentsParentIdParentDocumentRequestsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseListPropertyParentDocument>> {
        if (requestParameters['propertyId'] == null) {
            throw new runtime.RequiredError(
                'propertyId',
                'Required parameter "propertyId" was null or undefined when calling getPropertiesPropertiesPropertyIdParentsParentIdParentDocumentRequestsGet().'
            );
        }

        if (requestParameters['parentId'] == null) {
            throw new runtime.RequiredError(
                'parentId',
                'Required parameter "parentId" was null or undefined when calling getPropertiesPropertiesPropertyIdParentsParentIdParentDocumentRequestsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/properties/{property_id}/parents/{parent_id}/parent-document-requests`;
        urlPath = urlPath.replace(`{${"property_id"}}`, encodeURIComponent(String(requestParameters['propertyId'])));
        urlPath = urlPath.replace(`{${"parent_id"}}`, encodeURIComponent(String(requestParameters['parentId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiResponseListPropertyParentDocumentFromJSON(jsonValue));
    }

    /**
     * Get Properties
     */
    async getPropertiesPropertiesPropertyIdParentsParentIdParentDocumentRequestsGet(requestParameters: GetPropertiesPropertiesPropertyIdParentsParentIdParentDocumentRequestsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseListPropertyParentDocument> {
        const response = await this.getPropertiesPropertiesPropertyIdParentsParentIdParentDocumentRequestsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Property Parent Document Approval Request By Document Id
     */
    async getPropertyParentDocumentApprovalRequestByDocumentIdPropertiesPropertyIdParentsParentIdParentDocumentsParentDocIdGetRaw(requestParameters: GetPropertyParentDocumentApprovalRequestByDocumentIdPropertiesPropertyIdParentsParentIdParentDocumentsParentDocIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponsePropertyParentDocument>> {
        if (requestParameters['propertyId'] == null) {
            throw new runtime.RequiredError(
                'propertyId',
                'Required parameter "propertyId" was null or undefined when calling getPropertyParentDocumentApprovalRequestByDocumentIdPropertiesPropertyIdParentsParentIdParentDocumentsParentDocIdGet().'
            );
        }

        if (requestParameters['parentId'] == null) {
            throw new runtime.RequiredError(
                'parentId',
                'Required parameter "parentId" was null or undefined when calling getPropertyParentDocumentApprovalRequestByDocumentIdPropertiesPropertyIdParentsParentIdParentDocumentsParentDocIdGet().'
            );
        }

        if (requestParameters['parentDocId'] == null) {
            throw new runtime.RequiredError(
                'parentDocId',
                'Required parameter "parentDocId" was null or undefined when calling getPropertyParentDocumentApprovalRequestByDocumentIdPropertiesPropertyIdParentsParentIdParentDocumentsParentDocIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/properties/{property_id}/parents/{parent_id}/parent-documents/{parent_doc_id}`;
        urlPath = urlPath.replace(`{${"property_id"}}`, encodeURIComponent(String(requestParameters['propertyId'])));
        urlPath = urlPath.replace(`{${"parent_id"}}`, encodeURIComponent(String(requestParameters['parentId'])));
        urlPath = urlPath.replace(`{${"parent_doc_id"}}`, encodeURIComponent(String(requestParameters['parentDocId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiResponsePropertyParentDocumentFromJSON(jsonValue));
    }

    /**
     * Get Property Parent Document Approval Request By Document Id
     */
    async getPropertyParentDocumentApprovalRequestByDocumentIdPropertiesPropertyIdParentsParentIdParentDocumentsParentDocIdGet(requestParameters: GetPropertyParentDocumentApprovalRequestByDocumentIdPropertiesPropertyIdParentsParentIdParentDocumentsParentDocIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponsePropertyParentDocument> {
        const response = await this.getPropertyParentDocumentApprovalRequestByDocumentIdPropertiesPropertyIdParentsParentIdParentDocumentsParentDocIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Send Property Parent Document Approval Request
     */
    async sendPropertyParentDocumentApprovalRequestPropertiesPropertyIdParentsParentIdParentDocumentsParentDocIdPostRaw(requestParameters: SendPropertyParentDocumentApprovalRequestPropertiesPropertyIdParentsParentIdParentDocumentsParentDocIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponsePropertyParentDocument>> {
        if (requestParameters['propertyId'] == null) {
            throw new runtime.RequiredError(
                'propertyId',
                'Required parameter "propertyId" was null or undefined when calling sendPropertyParentDocumentApprovalRequestPropertiesPropertyIdParentsParentIdParentDocumentsParentDocIdPost().'
            );
        }

        if (requestParameters['parentId'] == null) {
            throw new runtime.RequiredError(
                'parentId',
                'Required parameter "parentId" was null or undefined when calling sendPropertyParentDocumentApprovalRequestPropertiesPropertyIdParentsParentIdParentDocumentsParentDocIdPost().'
            );
        }

        if (requestParameters['parentDocId'] == null) {
            throw new runtime.RequiredError(
                'parentDocId',
                'Required parameter "parentDocId" was null or undefined when calling sendPropertyParentDocumentApprovalRequestPropertiesPropertyIdParentsParentIdParentDocumentsParentDocIdPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/properties/{property_id}/parents/{parent_id}/parent-documents/{parent_doc_id}`;
        urlPath = urlPath.replace(`{${"property_id"}}`, encodeURIComponent(String(requestParameters['propertyId'])));
        urlPath = urlPath.replace(`{${"parent_id"}}`, encodeURIComponent(String(requestParameters['parentId'])));
        urlPath = urlPath.replace(`{${"parent_doc_id"}}`, encodeURIComponent(String(requestParameters['parentDocId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiResponsePropertyParentDocumentFromJSON(jsonValue));
    }

    /**
     * Send Property Parent Document Approval Request
     */
    async sendPropertyParentDocumentApprovalRequestPropertiesPropertyIdParentsParentIdParentDocumentsParentDocIdPost(requestParameters: SendPropertyParentDocumentApprovalRequestPropertiesPropertyIdParentsParentIdParentDocumentsParentDocIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponsePropertyParentDocument> {
        const response = await this.sendPropertyParentDocumentApprovalRequestPropertiesPropertyIdParentsParentIdParentDocumentsParentDocIdPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Sth
     */
    async sthPropertiesPropertyIdParentsParentIdParentDocumentsParentDocumentIdStatusRequestStatusPatchRaw(requestParameters: SthPropertiesPropertyIdParentsParentIdParentDocumentsParentDocumentIdStatusRequestStatusPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponsePropertyParentDocument>> {
        if (requestParameters['propertyId'] == null) {
            throw new runtime.RequiredError(
                'propertyId',
                'Required parameter "propertyId" was null or undefined when calling sthPropertiesPropertyIdParentsParentIdParentDocumentsParentDocumentIdStatusRequestStatusPatch().'
            );
        }

        if (requestParameters['parentId'] == null) {
            throw new runtime.RequiredError(
                'parentId',
                'Required parameter "parentId" was null or undefined when calling sthPropertiesPropertyIdParentsParentIdParentDocumentsParentDocumentIdStatusRequestStatusPatch().'
            );
        }

        if (requestParameters['parentDocumentId'] == null) {
            throw new runtime.RequiredError(
                'parentDocumentId',
                'Required parameter "parentDocumentId" was null or undefined when calling sthPropertiesPropertyIdParentsParentIdParentDocumentsParentDocumentIdStatusRequestStatusPatch().'
            );
        }

        if (requestParameters['requestStatus'] == null) {
            throw new runtime.RequiredError(
                'requestStatus',
                'Required parameter "requestStatus" was null or undefined when calling sthPropertiesPropertyIdParentsParentIdParentDocumentsParentDocumentIdStatusRequestStatusPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/properties/{property_id}/parents/{parent_id}/parent-documents/{parent_document_id}/status/{request_status}`;
        urlPath = urlPath.replace(`{${"property_id"}}`, encodeURIComponent(String(requestParameters['propertyId'])));
        urlPath = urlPath.replace(`{${"parent_id"}}`, encodeURIComponent(String(requestParameters['parentId'])));
        urlPath = urlPath.replace(`{${"parent_document_id"}}`, encodeURIComponent(String(requestParameters['parentDocumentId'])));
        urlPath = urlPath.replace(`{${"request_status"}}`, encodeURIComponent(String(requestParameters['requestStatus'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiResponsePropertyParentDocumentFromJSON(jsonValue));
    }

    /**
     * Sth
     */
    async sthPropertiesPropertyIdParentsParentIdParentDocumentsParentDocumentIdStatusRequestStatusPatch(requestParameters: SthPropertiesPropertyIdParentsParentIdParentDocumentsParentDocumentIdStatusRequestStatusPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponsePropertyParentDocument> {
        const response = await this.sthPropertiesPropertyIdParentsParentIdParentDocumentsParentDocumentIdStatusRequestStatusPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
