/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiResponsePropertyUser,
  HTTPValidationError,
} from '../models/index';
import {
    ApiResponsePropertyUserFromJSON,
    ApiResponsePropertyUserToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface GetPropertiesPropertiesPropertyIdUsersUserIdGetRequest {
    propertyId: string;
    userId: string;
}

/**
 * 
 */
export class IdentityApi extends runtime.BaseAPI {

    /**
     * Get Properties
     */
    async getPropertiesPropertiesPropertyIdUsersUserIdGetRaw(requestParameters: GetPropertiesPropertiesPropertyIdUsersUserIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponsePropertyUser>> {
        if (requestParameters['propertyId'] == null) {
            throw new runtime.RequiredError(
                'propertyId',
                'Required parameter "propertyId" was null or undefined when calling getPropertiesPropertiesPropertyIdUsersUserIdGet().'
            );
        }

        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getPropertiesPropertiesPropertyIdUsersUserIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/properties/{property_id}/users/{user_id}`;
        urlPath = urlPath.replace(`{${"property_id"}}`, encodeURIComponent(String(requestParameters['propertyId'])));
        urlPath = urlPath.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiResponsePropertyUserFromJSON(jsonValue));
    }

    /**
     * Get Properties
     */
    async getPropertiesPropertiesPropertyIdUsersUserIdGet(requestParameters: GetPropertiesPropertiesPropertyIdUsersUserIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponsePropertyUser> {
        const response = await this.getPropertiesPropertiesPropertyIdUsersUserIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
