/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiResponseListPropertyChild,
  ApiResponseListPropertyChildDocumentRequirement,
  ApiResponseListPropertyParentDocumentRequirement,
  ApiResponsePagedResponseProperty,
  ApiResponsePagedResponsePropertyChild,
  HTTPValidationError,
} from '../models/index';
import {
    ApiResponseListPropertyChildFromJSON,
    ApiResponseListPropertyChildToJSON,
    ApiResponseListPropertyChildDocumentRequirementFromJSON,
    ApiResponseListPropertyChildDocumentRequirementToJSON,
    ApiResponseListPropertyParentDocumentRequirementFromJSON,
    ApiResponseListPropertyParentDocumentRequirementToJSON,
    ApiResponsePagedResponsePropertyFromJSON,
    ApiResponsePagedResponsePropertyToJSON,
    ApiResponsePagedResponsePropertyChildFromJSON,
    ApiResponsePagedResponsePropertyChildToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface GetAllPropertyChildrenForGivenParentPropertiesPropertyIdParentsParentIdPropertyChildrenGetRequest {
    propertyId: any;
    parentId: any;
}

export interface GetAllPropertyChildrenPagedPropertiesPropertyIdPropertyChildrenGetRequest {
    propertyId: any;
    pageSize?: number;
    pageNumber?: number;
}

export interface GetDocumentRequirementsForGivenPropertyChildPropertiesPropertyIdChildrenChildIdDocumentRequirementsGetRequest {
    propertyId: any;
    childId: any;
}

export interface GetDocumentRequirementsForGivenPropertyParentPropertiesPropertyIdUsersUserIdParentDocumentRequirementsGetRequest {
    propertyId: any;
    userId: any;
}

export interface GetPropertiesPropertiesGetRequest {
    pageSize?: number;
    pageNumber?: number;
}

/**
 * 
 */
export class PropertyApi extends runtime.BaseAPI {

    /**
     * Get All Property Children For Given Parent
     */
    async getAllPropertyChildrenForGivenParentPropertiesPropertyIdParentsParentIdPropertyChildrenGetRaw(requestParameters: GetAllPropertyChildrenForGivenParentPropertiesPropertyIdParentsParentIdPropertyChildrenGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseListPropertyChild>> {
        if (requestParameters['propertyId'] == null) {
            throw new runtime.RequiredError(
                'propertyId',
                'Required parameter "propertyId" was null or undefined when calling getAllPropertyChildrenForGivenParentPropertiesPropertyIdParentsParentIdPropertyChildrenGet().'
            );
        }

        if (requestParameters['parentId'] == null) {
            throw new runtime.RequiredError(
                'parentId',
                'Required parameter "parentId" was null or undefined when calling getAllPropertyChildrenForGivenParentPropertiesPropertyIdParentsParentIdPropertyChildrenGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/properties/{property_id}/parents/{parent_id}/property-children`;
        urlPath = urlPath.replace(`{${"property_id"}}`, encodeURIComponent(String(requestParameters['propertyId'])));
        urlPath = urlPath.replace(`{${"parent_id"}}`, encodeURIComponent(String(requestParameters['parentId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiResponseListPropertyChildFromJSON(jsonValue));
    }

    /**
     * Get All Property Children For Given Parent
     */
    async getAllPropertyChildrenForGivenParentPropertiesPropertyIdParentsParentIdPropertyChildrenGet(requestParameters: GetAllPropertyChildrenForGivenParentPropertiesPropertyIdParentsParentIdPropertyChildrenGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseListPropertyChild> {
        const response = await this.getAllPropertyChildrenForGivenParentPropertiesPropertyIdParentsParentIdPropertyChildrenGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get All Property Children Paged
     */
    async getAllPropertyChildrenPagedPropertiesPropertyIdPropertyChildrenGetRaw(requestParameters: GetAllPropertyChildrenPagedPropertiesPropertyIdPropertyChildrenGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponsePagedResponsePropertyChild>> {
        if (requestParameters['propertyId'] == null) {
            throw new runtime.RequiredError(
                'propertyId',
                'Required parameter "propertyId" was null or undefined when calling getAllPropertyChildrenPagedPropertiesPropertyIdPropertyChildrenGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['pageSize'] != null) {
            queryParameters['page_size'] = requestParameters['pageSize'];
        }

        if (requestParameters['pageNumber'] != null) {
            queryParameters['page_number'] = requestParameters['pageNumber'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/properties/{property_id}/property-children`;
        urlPath = urlPath.replace(`{${"property_id"}}`, encodeURIComponent(String(requestParameters['propertyId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiResponsePagedResponsePropertyChildFromJSON(jsonValue));
    }

    /**
     * Get All Property Children Paged
     */
    async getAllPropertyChildrenPagedPropertiesPropertyIdPropertyChildrenGet(requestParameters: GetAllPropertyChildrenPagedPropertiesPropertyIdPropertyChildrenGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponsePagedResponsePropertyChild> {
        const response = await this.getAllPropertyChildrenPagedPropertiesPropertyIdPropertyChildrenGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Document Requirements For Given Property Child
     */
    async getDocumentRequirementsForGivenPropertyChildPropertiesPropertyIdChildrenChildIdDocumentRequirementsGetRaw(requestParameters: GetDocumentRequirementsForGivenPropertyChildPropertiesPropertyIdChildrenChildIdDocumentRequirementsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseListPropertyChildDocumentRequirement>> {
        if (requestParameters['propertyId'] == null) {
            throw new runtime.RequiredError(
                'propertyId',
                'Required parameter "propertyId" was null or undefined when calling getDocumentRequirementsForGivenPropertyChildPropertiesPropertyIdChildrenChildIdDocumentRequirementsGet().'
            );
        }

        if (requestParameters['childId'] == null) {
            throw new runtime.RequiredError(
                'childId',
                'Required parameter "childId" was null or undefined when calling getDocumentRequirementsForGivenPropertyChildPropertiesPropertyIdChildrenChildIdDocumentRequirementsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/properties/{property_id}/children/{child_id}/document-requirements`;
        urlPath = urlPath.replace(`{${"property_id"}}`, encodeURIComponent(String(requestParameters['propertyId'])));
        urlPath = urlPath.replace(`{${"child_id"}}`, encodeURIComponent(String(requestParameters['childId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiResponseListPropertyChildDocumentRequirementFromJSON(jsonValue));
    }

    /**
     * Get Document Requirements For Given Property Child
     */
    async getDocumentRequirementsForGivenPropertyChildPropertiesPropertyIdChildrenChildIdDocumentRequirementsGet(requestParameters: GetDocumentRequirementsForGivenPropertyChildPropertiesPropertyIdChildrenChildIdDocumentRequirementsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseListPropertyChildDocumentRequirement> {
        const response = await this.getDocumentRequirementsForGivenPropertyChildPropertiesPropertyIdChildrenChildIdDocumentRequirementsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Document Requirements For Given Property Parent
     */
    async getDocumentRequirementsForGivenPropertyParentPropertiesPropertyIdUsersUserIdParentDocumentRequirementsGetRaw(requestParameters: GetDocumentRequirementsForGivenPropertyParentPropertiesPropertyIdUsersUserIdParentDocumentRequirementsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseListPropertyParentDocumentRequirement>> {
        if (requestParameters['propertyId'] == null) {
            throw new runtime.RequiredError(
                'propertyId',
                'Required parameter "propertyId" was null or undefined when calling getDocumentRequirementsForGivenPropertyParentPropertiesPropertyIdUsersUserIdParentDocumentRequirementsGet().'
            );
        }

        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getDocumentRequirementsForGivenPropertyParentPropertiesPropertyIdUsersUserIdParentDocumentRequirementsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/properties/{property_id}/users/{user_id}/parent-document-requirements`;
        urlPath = urlPath.replace(`{${"property_id"}}`, encodeURIComponent(String(requestParameters['propertyId'])));
        urlPath = urlPath.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiResponseListPropertyParentDocumentRequirementFromJSON(jsonValue));
    }

    /**
     * Get Document Requirements For Given Property Parent
     */
    async getDocumentRequirementsForGivenPropertyParentPropertiesPropertyIdUsersUserIdParentDocumentRequirementsGet(requestParameters: GetDocumentRequirementsForGivenPropertyParentPropertiesPropertyIdUsersUserIdParentDocumentRequirementsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseListPropertyParentDocumentRequirement> {
        const response = await this.getDocumentRequirementsForGivenPropertyParentPropertiesPropertyIdUsersUserIdParentDocumentRequirementsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Properties
     */
    async getPropertiesPropertiesGetRaw(requestParameters: GetPropertiesPropertiesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponsePagedResponseProperty>> {
        const queryParameters: any = {};

        if (requestParameters['pageSize'] != null) {
            queryParameters['page_size'] = requestParameters['pageSize'];
        }

        if (requestParameters['pageNumber'] != null) {
            queryParameters['page_number'] = requestParameters['pageNumber'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/properties`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiResponsePagedResponsePropertyFromJSON(jsonValue));
    }

    /**
     * Get Properties
     */
    async getPropertiesPropertiesGet(requestParameters: GetPropertiesPropertiesGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponsePagedResponseProperty> {
        const response = await this.getPropertiesPropertiesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
