/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiResponseParentDocument,
  ApiResponseStr,
  DOCUMENTTYPE,
  HTTPValidationError,
} from '../models/index';
import {
    ApiResponseParentDocumentFromJSON,
    ApiResponseParentDocumentToJSON,
    ApiResponseStrFromJSON,
    ApiResponseStrToJSON,
    DOCUMENTTYPEFromJSON,
    DOCUMENTTYPEToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface GetDocumentUrlByFilePathDocumentsFilePathGetRequest {
    filePath: string;
}

export interface GetParentDocumentByTypeParentsParentIdDocumentsDocumentTypeGetRequest {
    parentId: string;
    documentType: any;
}

export interface GetParentDocumentUrlByDocumentIdParentDocumentsDocIdGetRequest {
    docId: string;
}

export interface SaveParentDocumentParentsParentIdDocumentsDocumentTypePostRequest {
    parentId: string;
    documentType: DOCUMENTTYPE;
    file: Blob;
}

/**
 * 
 */
export class ReportingApi extends runtime.BaseAPI {

    /**
     * Get Document Url By File Path
     */
    async getDocumentUrlByFilePathDocumentsFilePathGetRaw(requestParameters: GetDocumentUrlByFilePathDocumentsFilePathGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseStr>> {
        if (requestParameters['filePath'] == null) {
            throw new runtime.RequiredError(
                'filePath',
                'Required parameter "filePath" was null or undefined when calling getDocumentUrlByFilePathDocumentsFilePathGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/documents/{file_path}`;
        urlPath = urlPath.replace(`{${"file_path"}}`, encodeURIComponent(String(requestParameters['filePath'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiResponseStrFromJSON(jsonValue));
    }

    /**
     * Get Document Url By File Path
     */
    async getDocumentUrlByFilePathDocumentsFilePathGet(requestParameters: GetDocumentUrlByFilePathDocumentsFilePathGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseStr> {
        const response = await this.getDocumentUrlByFilePathDocumentsFilePathGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Parent Document By Type
     */
    async getParentDocumentByTypeParentsParentIdDocumentsDocumentTypeGetRaw(requestParameters: GetParentDocumentByTypeParentsParentIdDocumentsDocumentTypeGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseParentDocument>> {
        if (requestParameters['parentId'] == null) {
            throw new runtime.RequiredError(
                'parentId',
                'Required parameter "parentId" was null or undefined when calling getParentDocumentByTypeParentsParentIdDocumentsDocumentTypeGet().'
            );
        }

        if (requestParameters['documentType'] == null) {
            throw new runtime.RequiredError(
                'documentType',
                'Required parameter "documentType" was null or undefined when calling getParentDocumentByTypeParentsParentIdDocumentsDocumentTypeGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/parents/{parent_id}/documents/{document_type}`;
        urlPath = urlPath.replace(`{${"parent_id"}}`, encodeURIComponent(String(requestParameters['parentId'])));
        urlPath = urlPath.replace(`{${"document_type"}}`, encodeURIComponent(String(requestParameters['documentType'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiResponseParentDocumentFromJSON(jsonValue));
    }

    /**
     * Get Parent Document By Type
     */
    async getParentDocumentByTypeParentsParentIdDocumentsDocumentTypeGet(requestParameters: GetParentDocumentByTypeParentsParentIdDocumentsDocumentTypeGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseParentDocument> {
        const response = await this.getParentDocumentByTypeParentsParentIdDocumentsDocumentTypeGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Parent Document Url By Document Id
     */
    async getParentDocumentUrlByDocumentIdParentDocumentsDocIdGetRaw(requestParameters: GetParentDocumentUrlByDocumentIdParentDocumentsDocIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseStr>> {
        if (requestParameters['docId'] == null) {
            throw new runtime.RequiredError(
                'docId',
                'Required parameter "docId" was null or undefined when calling getParentDocumentUrlByDocumentIdParentDocumentsDocIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/parent-documents/{doc_id}`;
        urlPath = urlPath.replace(`{${"doc_id"}}`, encodeURIComponent(String(requestParameters['docId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiResponseStrFromJSON(jsonValue));
    }

    /**
     * Get Parent Document Url By Document Id
     */
    async getParentDocumentUrlByDocumentIdParentDocumentsDocIdGet(requestParameters: GetParentDocumentUrlByDocumentIdParentDocumentsDocIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseStr> {
        const response = await this.getParentDocumentUrlByDocumentIdParentDocumentsDocIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Save Parent Document
     */
    async saveParentDocumentParentsParentIdDocumentsDocumentTypePostRaw(requestParameters: SaveParentDocumentParentsParentIdDocumentsDocumentTypePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiResponseParentDocument>> {
        if (requestParameters['parentId'] == null) {
            throw new runtime.RequiredError(
                'parentId',
                'Required parameter "parentId" was null or undefined when calling saveParentDocumentParentsParentIdDocumentsDocumentTypePost().'
            );
        }

        if (requestParameters['documentType'] == null) {
            throw new runtime.RequiredError(
                'documentType',
                'Required parameter "documentType" was null or undefined when calling saveParentDocumentParentsParentIdDocumentsDocumentTypePost().'
            );
        }

        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling saveParentDocumentParentsParentIdDocumentsDocumentTypePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }


        let urlPath = `/parents/{parent_id}/documents/{document_type}`;
        urlPath = urlPath.replace(`{${"parent_id"}}`, encodeURIComponent(String(requestParameters['parentId'])));
        urlPath = urlPath.replace(`{${"document_type"}}`, encodeURIComponent(String(requestParameters['documentType'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiResponseParentDocumentFromJSON(jsonValue));
    }

    /**
     * Save Parent Document
     */
    async saveParentDocumentParentsParentIdDocumentsDocumentTypePost(requestParameters: SaveParentDocumentParentsParentIdDocumentsDocumentTypePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiResponseParentDocument> {
        const response = await this.saveParentDocumentParentsParentIdDocumentsDocumentTypePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
