export const authSchema = {
  user: {
    id: { type: "string", primaryKey: true },
    name: "string",
    email: "string",
    emailVerified: "boolean",
    image: "string?",
    createdAt: "date",
    updatedAt: "date",
  },
  session: {
    id: { type: "string", primaryKey: true },
    expiresAt: "date",
    token: "string",
    createdAt: "date",
    updatedAt: "date",
    ipAddress: "string?",
    userAgent: "string?",
    userId: { type: "string", references: "user" },
  },
  account: {
    id: { type: "string", primaryKey: true },
    accountId: "string",
    providerId: "string",
    userId: { type: "string", references: "user" },
    accessToken: "string?",
    refreshToken: "string?",
    idToken: "string?",
    accessTokenExpiresAt: "date?",
    refreshTokenExpiresAt: "date?",
    scope: "string?",
    password: "string?",
    createdAt: "date",
    updatedAt: "date",
  },
  verification: {
    id: { type: "string", primaryKey: true },
    identifier: "string",
    value: "string",
    expiresAt: "date",
    createdAt: "date",
    updatedAt: "date",
  },
};
