/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/properties/{property_id}/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Properties */
        get: operations["get_properties_properties__property_id__users__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parents/{parent_id}/documents/{document_type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Parent Document By Type */
        get: operations["get_parent_document_by_type_parents__parent_id__documents__document_type__get"];
        put?: never;
        /** Save Parent Document */
        post: operations["save_parent_document_parents__parent_id__documents__document_type__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parent-documents/{doc_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Parent Document Url By Document Id */
        get: operations["get_parent_document_url_by_document_id_parent_documents__doc_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{file_path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document Url By File Path */
        get: operations["get_document_url_by_file_path_documents__file_path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/children/{child_id}/documents/{document_type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Child Document By Type */
        get: operations["get_child_document_by_type_children__child_id__documents__document_type__get"];
        put?: never;
        /** Save Child Document */
        post: operations["save_child_document_children__child_id__documents__document_type__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/children-documents/{doc_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Child Document Url By Document Id */
        get: operations["get_child_document_url_by_document_id_children_documents__doc_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parent-partners/{partner_id}/documents/{document_type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Parent Partner Document By Type */
        get: operations["get_parent_partner_document_by_type_parent_partners__partner_id__documents__document_type__get"];
        put?: never;
        /** Save Parent Partner Document */
        post: operations["save_parent_partner_document_parent_partners__partner_id__documents__document_type__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/properties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Properties */
        get: operations["get_properties_properties_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/properties/{property_id}/users/{user_id}/parent-document-requirements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document Requirements For Given Property Parent */
        get: operations["get_document_requirements_for_given_property_parent_properties__property_id__users__user_id__parent_document_requirements_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/properties/{property_id}/parents/{parent_id}/property-children": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get All Property Children For Given Parent */
        get: operations["get_all_property_children_for_given_parent_properties__property_id__parents__parent_id__property_children_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/properties/{property_id}/children/{child_id}/document-requirements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document Requirements For Given Property Child */
        get: operations["get_document_requirements_for_given_property_child_properties__property_id__children__child_id__document_requirements_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/properties/{property_id}/property-children": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get All Property Children Paged */
        get: operations["get_all_property_children_paged_properties__property_id__property_children_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/properties/{property_id}/parent-partners/{partner_id}/parent-document-requirements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document Requirements For Given Property Parent Partner */
        get: operations["get_document_requirements_for_given_property_parent_partner_properties__property_id__parent_partners__partner_id__parent_document_requirements_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/properties/{property_id}/parents/{parent_id}/parent-document-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get All Document Approval Requests For Given Property Parent */
        get: operations["get_all_document_approval_requests_for_given_property_parent_properties__property_id__parents__parent_id__parent_document_requests_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/properties/{property_id}/children/{child_id}/child-document-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get All Document Approval Requests For Given Property Child */
        get: operations["get_all_document_approval_requests_for_given_property_child_properties__property_id__children__child_id__child_document_requests_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/properties/{property_id}/parents/{parent_id}/parent-documents/{parent_doc_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Property Parent Document Approval Request By Document Id */
        get: operations["get_property_parent_document_approval_request_by_document_id_properties__property_id__parents__parent_id__parent_documents__parent_doc_id__get"];
        put?: never;
        /** Send Property Parent Document Approval Request */
        post: operations["send_property_parent_document_approval_request_properties__property_id__parents__parent_id__parent_documents__parent_doc_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/properties/{property_id}/parent-document-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get All Document Approval Requests For Given Property */
        get: operations["get_all_document_approval_requests_for_given_property_properties__property_id__parent_document_requests_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/properties/{property_id}/parents/{parent_id}/parent-documents/{parent_document_id}/status/{request_status}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Set Property Parent Document Request Status */
        patch: operations["set_property_parent_document_request_status_properties__property_id__parents__parent_id__parent_documents__parent_document_id__status__request_status__patch"];
        trace?: never;
    };
    "/properties/{property_id}/child-document-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get All Child Document Approval Requests For Given Property */
        get: operations["get_all_child_document_approval_requests_for_given_property_properties__property_id__child_document_requests_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/properties/{property_id}/children/{child_id}/children-documents/{child_document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send Property Child Document Approval Request */
        post: operations["send_property_child_document_approval_request_properties__property_id__children__child_id__children_documents__child_document_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/properties/{property_id}/children/{child_id}/child-documents/{child_document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Property Child Document Approval Request By Document Id */
        get: operations["get_property_child_document_approval_request_by_document_id_properties__property_id__children__child_id__child_documents__child_document_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/properties/{property_id}/children/{child_id}/children-documents/{child_document_id}/status/{request_status}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Set Property Child Document Request Status */
        patch: operations["set_property_child_document_request_status_properties__property_id__children__child_id__children_documents__child_document_id__status__request_status__patch"];
        trace?: never;
    };
    "/properties/{property_id}/parent-partners/{partner_id}/document-requests/{parent_partner_document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send Property Parent Partner Document Approval Request */
        post: operations["send_property_parent_partner_document_approval_request_properties__property_id__parent_partners__partner_id__document_requests__parent_partner_document_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/properties/{property_id}/parent-partners/{partner_id}/parent-document-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get All Document Approval Requests For Given Property Parent Partner */
        get: operations["get_all_document_approval_requests_for_given_property_parent_partner_properties__property_id__parent_partners__partner_id__parent_document_requests_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/properties/{property_id}/parent-partners/{partner_id}/parent-documents/{parent_partner_document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Property Parent Partner Document Approval Request By Document Id */
        get: operations["get_property_parent_partner_document_approval_request_by_document_id_properties__property_id__parent_partners__partner_id__parent_documents__parent_partner_document_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_save_child_document_children__child_id__documents__document_type__post */
        Body_save_child_document_children__child_id__documents__document_type__post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** Body_save_parent_document_parents__parent_id__documents__document_type__post */
        Body_save_parent_document_parents__parent_id__documents__document_type__post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** Body_save_parent_partner_document_parent_partners__partner_id__documents__document_type__post */
        Body_save_parent_partner_document_parent_partners__partner_id__documents__document_type__post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /**
         * CHILD_CONDITION_KEY
         * @enum {string}
         */
        CHILD_CONDITION_KEY: "has_disability" | "is_from_single_parent_family";
        /**
         * CHILD_DOCUMENT_TYPE
         * @enum {string}
         */
        CHILD_DOCUMENT_TYPE: "disability_proof" | "single_parent_family_proof";
        /**
         * CONDITION_KEY
         * @enum {string}
         */
        CONDITION_KEY: "is_employed" | "is_self_employed" | "is_student" | "filed_tax_in_desired_location" | "resides_in_desired_location";
        /** ChildDocument */
        ChildDocument: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Child Id
             * Format: uuid
             */
            child_id: string;
            document_type: components["schemas"]["CHILD_DOCUMENT_TYPE"];
            /** File Path */
            file_path: string;
        };
        /**
         * DOCUMENT_TYPE
         * @enum {string}
         */
        DOCUMENT_TYPE: "employment_proof" | "self_employment_proof" | "student_proof" | "filed_tax_in_desired_location_proof" | "resides_in_desired_location_proof";
        /** HTTPError */
        HTTPError: {
            /** Code */
            code: number;
            /** Message */
            message: string;
        };
        /**
         * PROPERTY_USER_ROLE
         * @enum {string}
         */
        PROPERTY_USER_ROLE: "admin" | "parent";
        /** PagedResponse[PropertyChildDocument] */
        PagedResponse_PropertyChildDocument_: {
            /** Items */
            items: components["schemas"]["PropertyChildDocument"][];
            /** Total */
            total: number;
            /** Page Number */
            page_number: number;
            /** Page Size */
            page_size: number;
            /** Has Next Page */
            has_next_page: boolean;
            /** Has Previous Page */
            has_previous_page: boolean;
            /** Total Pages */
            total_pages: number;
        };
        /** PagedResponse[PropertyChild] */
        PagedResponse_PropertyChild_: {
            /** Items */
            items: components["schemas"]["PropertyChild"][];
            /** Total */
            total: number;
            /** Page Number */
            page_number: number;
            /** Page Size */
            page_size: number;
            /** Has Next Page */
            has_next_page: boolean;
            /** Has Previous Page */
            has_previous_page: boolean;
            /** Total Pages */
            total_pages: number;
        };
        /** PagedResponse[PropertyParentDocument] */
        PagedResponse_PropertyParentDocument_: {
            /** Items */
            items: components["schemas"]["PropertyParentDocument"][];
            /** Total */
            total: number;
            /** Page Number */
            page_number: number;
            /** Page Size */
            page_size: number;
            /** Has Next Page */
            has_next_page: boolean;
            /** Has Previous Page */
            has_previous_page: boolean;
            /** Total Pages */
            total_pages: number;
        };
        /** PagedResponse[Property] */
        PagedResponse_Property_: {
            /** Items */
            items: components["schemas"]["Property"][];
            /** Total */
            total: number;
            /** Page Number */
            page_number: number;
            /** Page Size */
            page_size: number;
            /** Has Next Page */
            has_next_page: boolean;
            /** Has Previous Page */
            has_previous_page: boolean;
            /** Total Pages */
            total_pages: number;
        };
        /** ParentDocument */
        ParentDocument: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            document_type: components["schemas"]["DOCUMENT_TYPE"];
            /** File Path */
            file_path: string;
        };
        /** ParentPartnerDocument */
        ParentPartnerDocument: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Partner Id
             * Format: uuid
             */
            partner_id: string;
            document_type: components["schemas"]["DOCUMENT_TYPE"];
            /** File Path */
            file_path: string;
        };
        /** Property */
        Property: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
        };
        /** PropertyChild */
        PropertyChild: {
            /**
             * Property Id
             * Format: uuid
             */
            property_id: string;
            /**
             * Child Id
             * Format: uuid
             */
            child_id: string;
            /** Points */
            points: number;
            /** Approved */
            approved: boolean;
        };
        /** PropertyChildDocument */
        PropertyChildDocument: {
            /**
             * Property Id
             * Format: uuid
             */
            property_id: string;
            /**
             * Child Id
             * Format: uuid
             */
            child_id: string;
            /**
             * Child Document Id
             * Format: uuid
             */
            child_document_id: string;
            request_status: components["schemas"]["REQUEST_STATUS"];
            /** Approved By */
            approved_by: string | null;
            document_type: components["schemas"]["CHILD_DOCUMENT_TYPE"];
        };
        /** PropertyChildDocumentRequest */
        PropertyChildDocumentRequest: {
            document_type: components["schemas"]["CHILD_DOCUMENT_TYPE"];
        };
        /** PropertyChildDocumentRequirement */
        PropertyChildDocumentRequirement: {
            /**
             * Property Id
             * Format: uuid
             */
            property_id: string;
            document_type: components["schemas"]["CHILD_DOCUMENT_TYPE"];
            requirement_type: components["schemas"]["REQUIREMENT_TYPE"];
            condition_key: components["schemas"]["CHILD_CONDITION_KEY"];
            /** Point Value */
            point_value: number;
        };
        /** PropertyParentDocument */
        PropertyParentDocument: {
            /**
             * Property Id
             * Format: uuid
             */
            property_id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * Parent Document Id
             * Format: uuid
             */
            parent_document_id: string;
            request_status: components["schemas"]["REQUEST_STATUS"];
            /** Approved By */
            approved_by: string | null;
            document_type: components["schemas"]["DOCUMENT_TYPE"];
        };
        /** PropertyParentDocumentRequest */
        PropertyParentDocumentRequest: {
            document_type: components["schemas"]["DOCUMENT_TYPE"];
        };
        /** PropertyParentDocumentRequirement */
        PropertyParentDocumentRequirement: {
            /**
             * Property Id
             * Format: uuid
             */
            property_id: string;
            document_type: components["schemas"]["DOCUMENT_TYPE"];
            requirement_type: components["schemas"]["REQUIREMENT_TYPE"];
            condition_key: components["schemas"]["CONDITION_KEY"];
            /** Point Value */
            point_value: number;
        };
        /** PropertyParentPartnerDocument */
        PropertyParentPartnerDocument: {
            /**
             * Property Id
             * Format: uuid
             */
            property_id: string;
            /**
             * Partner Id
             * Format: uuid
             */
            partner_id: string;
            /**
             * Parent Partner Document Id
             * Format: uuid
             */
            parent_partner_document_id: string;
            request_status: components["schemas"]["REQUEST_STATUS"];
            /** Approved By */
            approved_by: string | null;
            document_type: components["schemas"]["DOCUMENT_TYPE"];
        };
        /** PropertyParentPartnerDocumentRequest */
        PropertyParentPartnerDocumentRequest: {
            document_type: components["schemas"]["DOCUMENT_TYPE"];
        };
        /** PropertyUser */
        PropertyUser: {
            /**
             * Property Id
             * Format: uuid
             */
            property_id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            role: components["schemas"]["PROPERTY_USER_ROLE"];
        };
        /**
         * REQUEST_STATUS
         * @enum {string}
         */
        REQUEST_STATUS: "pending" | "approved" | "rejected";
        /**
         * REQUIREMENT_TYPE
         * @enum {string}
         */
        REQUIREMENT_TYPE: "always" | "conditional";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_properties_properties__property_id__users__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                property_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyUser"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
        };
    };
    get_parent_document_by_type_parents__parent_id__documents__document_type__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                parent_id: string;
                document_type: unknown;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParentDocument"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
        };
    };
    save_parent_document_parents__parent_id__documents__document_type__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                parent_id: string;
                document_type: components["schemas"]["DOCUMENT_TYPE"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_save_parent_document_parents__parent_id__documents__document_type__post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParentDocument"];
                };
            };
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParentDocument"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
        };
    };
    get_parent_document_url_by_document_id_parent_documents__doc_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
        };
    };
    get_document_url_by_file_path_documents__file_path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
        };
    };
    get_child_document_by_type_children__child_id__documents__document_type__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                child_id: string;
                document_type: components["schemas"]["CHILD_DOCUMENT_TYPE"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChildDocument"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
        };
    };
    save_child_document_children__child_id__documents__document_type__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                child_id: string;
                document_type: components["schemas"]["CHILD_DOCUMENT_TYPE"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_save_child_document_children__child_id__documents__document_type__post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChildDocument"];
                };
            };
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChildDocument"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
        };
    };
    get_child_document_url_by_document_id_children_documents__doc_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
        };
    };
    get_parent_partner_document_by_type_parent_partners__partner_id__documents__document_type__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                partner_id: string;
                document_type: unknown;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParentPartnerDocument"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
        };
    };
    save_parent_partner_document_parent_partners__partner_id__documents__document_type__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                partner_id: string;
                document_type: components["schemas"]["DOCUMENT_TYPE"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_save_parent_partner_document_parent_partners__partner_id__documents__document_type__post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParentPartnerDocument"];
                };
            };
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParentPartnerDocument"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
        };
    };
    get_properties_properties_get: {
        parameters: {
            query?: {
                page_size?: number;
                page_number?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedResponse_Property_"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
        };
    };
    get_document_requirements_for_given_property_parent_properties__property_id__users__user_id__parent_document_requirements_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                property_id: unknown;
                user_id: unknown;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyParentDocumentRequirement"][];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
        };
    };
    get_all_property_children_for_given_parent_properties__property_id__parents__parent_id__property_children_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                property_id: unknown;
                parent_id: unknown;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyChild"][];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
        };
    };
    get_document_requirements_for_given_property_child_properties__property_id__children__child_id__document_requirements_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                property_id: unknown;
                child_id: unknown;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyChildDocumentRequirement"][];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
        };
    };
    get_all_property_children_paged_properties__property_id__property_children_get: {
        parameters: {
            query?: {
                page_size?: number;
                page_number?: number;
            };
            header?: never;
            path: {
                property_id: unknown;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedResponse_PropertyChild_"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
        };
    };
    get_document_requirements_for_given_property_parent_partner_properties__property_id__parent_partners__partner_id__parent_document_requirements_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                property_id: string;
                partner_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyParentDocumentRequirement"][];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
        };
    };
    get_all_document_approval_requests_for_given_property_parent_properties__property_id__parents__parent_id__parent_document_requests_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                property_id: string;
                parent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyParentDocument"][];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
        };
    };
    get_all_document_approval_requests_for_given_property_child_properties__property_id__children__child_id__child_document_requests_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                property_id: string;
                child_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyChildDocument"][];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
        };
    };
    get_property_parent_document_approval_request_by_document_id_properties__property_id__parents__parent_id__parent_documents__parent_doc_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                property_id: string;
                parent_id: string;
                parent_doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyParentDocument"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
        };
    };
    send_property_parent_document_approval_request_properties__property_id__parents__parent_id__parent_documents__parent_doc_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                property_id: string;
                parent_id: string;
                parent_doc_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PropertyParentDocumentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyParentDocument"];
                };
            };
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyParentDocument"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
        };
    };
    get_all_document_approval_requests_for_given_property_properties__property_id__parent_document_requests_get: {
        parameters: {
            query?: {
                page_size?: number;
                page_number?: number;
            };
            header?: never;
            path: {
                property_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedResponse_PropertyParentDocument_"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
        };
    };
    set_property_parent_document_request_status_properties__property_id__parents__parent_id__parent_documents__parent_document_id__status__request_status__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                property_id: string;
                parent_id: string;
                parent_document_id: string;
                request_status: components["schemas"]["REQUEST_STATUS"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyParentDocument"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
        };
    };
    get_all_child_document_approval_requests_for_given_property_properties__property_id__child_document_requests_get: {
        parameters: {
            query?: {
                page_size?: number;
                page_number?: number;
            };
            header?: never;
            path: {
                property_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedResponse_PropertyChildDocument_"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
        };
    };
    send_property_child_document_approval_request_properties__property_id__children__child_id__children_documents__child_document_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                property_id: string;
                child_id: string;
                child_document_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PropertyChildDocumentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyChildDocument"];
                };
            };
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyChildDocument"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
        };
    };
    get_property_child_document_approval_request_by_document_id_properties__property_id__children__child_id__child_documents__child_document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                property_id: string;
                child_id: string;
                child_document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyChildDocument"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
        };
    };
    set_property_child_document_request_status_properties__property_id__children__child_id__children_documents__child_document_id__status__request_status__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                property_id: string;
                child_id: string;
                child_document_id: string;
                request_status: components["schemas"]["REQUEST_STATUS"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyChildDocument"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
        };
    };
    send_property_parent_partner_document_approval_request_properties__property_id__parent_partners__partner_id__document_requests__parent_partner_document_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                property_id: string;
                partner_id: string;
                parent_partner_document_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PropertyParentPartnerDocumentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyParentPartnerDocument"];
                };
            };
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyParentPartnerDocument"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
        };
    };
    get_all_document_approval_requests_for_given_property_parent_partner_properties__property_id__parent_partners__partner_id__parent_document_requests_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                property_id: string;
                partner_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyParentPartnerDocument"][];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
        };
    };
    get_property_parent_partner_document_approval_request_by_document_id_properties__property_id__parent_partners__partner_id__parent_documents__parent_partner_document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                property_id: string;
                partner_id: string;
                parent_partner_document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyParentPartnerDocument"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
        };
    };
}
